#!/usr/bin/env python3
from __future__ import annotations
import unittest
from pathlib import Path
ROOT = Path(__file__).resolve().parent
PAGES = ['revenue/production_survival/outreach.md', 'revenue/production_survival/marketplaces.md', 'revenue/production_survival/spend_containment_sprint.md', 'revenue/production_survival/prospect_signals.md', 'revenue/qlabs_qconnect_cutover/README.md', 'revenue/qlabs_qconnect_cutover/receipt.md', 'revenue/checkout_capability/README.md', 'revenue/highpower_ssf_receiving_gate/README.md', 'revenue/swarm_mail/README.md', 'revenue/made_scientific_princeton_rapid_qc/README.md', 'revenue/aquatrace_work_order_c_reporting_offline/README.md', 'revenue/elevatebio_pittsburgh_replication/receipt.md', 'revenue/csanalytical_expansion_crossline_lims/receipt.md', 'revenue/roslinct_hopkinton_paperless_qc/receipt.md', 'revenue/subzero_buyers/README.md', 'revenue/reply_to_revenue/README.md', 'revenue/portfolio_overdrive/README.md', 'revenue/portfolio_overdrive/source_ledger.md', 'revenue/portfolio_overdrive/dissent.md', 'revenue/human_outcomes/README.md', 'revenue/human_outcomes/fulfillment.md', 'revenue/eagletrax_split_sample_preflight/receipt.md', 'revenue/distribution/README.md', 'revenue/weck_coc_preaccession_validator/README.md', 'revenue/weck_coc_preaccession_validator/receipt.md', 'revenue/dio/README.md', 'revenue/ats_asphalt_spec_result_lims/receipt.md', 'revenue/aquatrace_work_order_b_production_foundation/README.md', 'revenue/sharp_rtu_vial_isolator_lineage/receipt.md', 'revenue/data/license_decision_package.md', 'revenue/lm_gtm_index/README.md', 'revenue/wayne-smart-api/README.md', 'revenue/marketing_sales/README.md', 'revenue/clark_d4172_proficiency/receipt.md', 'revenue/ace_qat_thermal_rheology_capacity/receipt.md', 'revenue/road_barbados_ocr/README.md', 'revenue/checkout_handoff/README.md', 'revenue/checkout_handoff/stripe_event_bridge.md', 'revenue/hive_community_events/README.md', 'revenue/hive_community_events/CALENDAR.md', 'revenue/hive_community_events/RESULTS_EXPORT.md', 'revenue/hive_community_events/RESULTS_EXPORT_HTML.md', 'revenue/hive_community_events/KNIGHT_PACK.md', 'revenue/hive_community_events/CHESS_CHALLENGES.md', 'revenue/spark-x25-math-challenge/README.md', 'revenue/fleet_work_order/README.md', 'revenue/fleet_work_order/receipt.md', 'revenue/ptl_controlled_sample_order_preflight/README.md', 'revenue/preinnewhof_pfas_fieldblank_gate/receipt.md', 'revenue/savant_fe8_order_report/receipt.md', 'revenue/sanair_asbestos_coc_router/README.md', 'revenue/agents_for_humans/README.md', 'revenue/agents_for_humans/SOURCE_FIDELITY.md', 'revenue/agents_for_humans/VALIDATION.md', 'revenue/agents_for_humans/ARCHITECTURE.md', 'revenue/scope_to_delivery/README.md', 'revenue/ddl_crosssite_method_proficiency/README.md', 'revenue/luvak_ssa_lab_analytics_cutover/receipt.md', 'revenue/big-onion-hold-rescue/README.md', 'revenue/subzero_gtm/README.md']
REQUIRED = ["https://webmcp-pad.vercel.app/", "1.4.5"]
class T(unittest.TestCase):
    def test_all(self):
        for name in PAGES:
            with self.subTest(page=name):
                text=(ROOT/name).read_text(encoding='utf-8')
                for n in REQUIRED: self.assertIn(n, text)
if __name__ == '__main__':
    unittest.main()
