#!/usr/bin/env python3
from __future__ import annotations
import unittest
from pathlib import Path
ROOT = Path(__file__).resolve().parent
PAGES = ['revenue/subzero_gtm/source_ledger.md', 'revenue/subzero_gtm/dissent.md', 'revenue/open_model_release_receipt/README.md', 'revenue/hive_campaign_router/README.md', 'revenue/hive_campaign_router/NOTICE.md', 'revenue/lexington_mrf_diversion_gate/receipt.md', 'revenue/apl_fda_polymer_compliance_dossier_lims/README.md', 'revenue/kincell_rtp_qc_release_bridge/README.md', 'revenue/aquatrace_ops_acceptance/README.md', 'revenue/dealer_service_lead_rescue/receipt.md', 'revenue/outcome_commerce/README.md', 'revenue/trace_sila_ml_iatf/receipt.md', 'revenue/oregon_brewlab_sample_report/receipt.md', 'revenue/baddl_eia_accession_release/receipt.md', 'revenue/chemtechford_short_hold_intake_lims/README.md', 'revenue/pcl_scope_sla_routing/README.md', 'revenue/website_people_email_book/README.md', 'revenue/payment_ready/README.md', 'revenue/payment_ready/source_ledger.md', 'revenue/payment_ready/evidence_contract.md', 'revenue/payment_ready/outreach.md', 'revenue/payment_ready/rails.md', 'revenue/payment_ready/private_input_manifest.md', 'revenue/payment_ready/processor_handoff.md', 'revenue/payment_ready/buyer_pack.md', 'revenue/payment_ready/dissent.md', 'revenue/slo_cls_cutover_evidence/receipt.md', 'revenue/rmb_crosssite_courier_accession/receipt.md', 'revenue/gosim2026/README.md', 'revenue/ward_feed_nirs_intake_validator/receipt.md', 'revenue/posted_work_discovery/README.md', 'revenue/posted_work_discovery/handoff_agent_survival_proof.md', 'revenue/posted_work_discovery/sites.md', 'revenue/posted_work_discovery/lims.md', 'revenue/posted_work_discovery/ai_agent_work.md', 'revenue/payment_capability/README.md', 'revenue/ait_mn_metrc_capacity_gate/receipt.md', 'revenue/elyan-human-funnel-stage1-20260909/ASSET_PACK.md', 'revenue/sgspsi_thermal_rheology_lineage/receipt.md', 'revenue/business_packs_marketing/README.md', 'revenue/business_packs_marketing/DATA_BUYING.md', 'revenue/business_packs_marketing/PRICE_ANCHORS.md', 'revenue/business_packs_marketing/LAW_AND_POLICY_FLAGS.md', 'revenue/business_packs_marketing/MESSAGING_ANGLE.md', 'revenue/business_packs_marketing/PAPERWORK.md', 'revenue/business_packs_marketing/BUYER_TIERS.md', 'revenue/business_packs_marketing/X_ADS_BRIEF.md', 'revenue/business_packs_marketing/ADVERTISING_GENERAL.md', 'revenue/business_packs_marketing/FERTILE_GROUND.md', 'revenue/right_now/README.md', 'revenue/right_now/proof_packet.md', 'revenue/pace_lebanon_microbial_volume_evidence/receipt.md', 'revenue/rosecity_olcc_metrc_sampling/receipt.md', 'revenue/torrent_workorder_commissioning/README.md', 'revenue/cornell_craft_beverage_intake/receipt.md', 'revenue/aquatrace_work_order_f_release_readiness/README.md', 'revenue/agriseed_rush_work_allocator/README.md', 'revenue/expert_networks/scheduling.md', 'revenue/expert_networks/response_templates.md', 'revenue/westpak_scope_capacity_routing/README.md']
REQUIRED = ["https://webmcp-pad.vercel.app/", "1.4.5"]
class T(unittest.TestCase):
    def test_all(self):
        for name in PAGES:
            with self.subTest(page=name):
                text=(ROOT/name).read_text(encoding='utf-8')
                for n in REQUIRED: self.assertIn(n, text)
if __name__ == '__main__':
    unittest.main()
