"""Stable schemas and state names for the connector-native pacemaker."""

SCHEMA = "commons-github-content-write-intent/v2"
RECEIPT_SCHEMA = "commons-github-content-write-receipt/v2"
DB_SCHEMA = "commons-github-content-write-pacemaker-db/v2"
QUEUED = "QUEUED"
DISPATCHING = "DISPATCHING"
COOLDOWN = "COOLDOWN"
COMMITTED = "COMMITTED"
REJECTED = "REJECTED"
RECONCILE_REQUIRED = "RECONCILE_REQUIRED"
OPERATOR_COMMITTED = "OPERATOR_OBSERVED_COMMITTED"
OPERATOR_REJECTED = "OPERATOR_OBSERVED_REJECTED"
ALL_STATES = {
    QUEUED, DISPATCHING, COOLDOWN, COMMITTED, REJECTED,
    RECONCILE_REQUIRED, OPERATOR_COMMITTED, OPERATOR_REJECTED,
}
MAX_BYTES = 1024 * 1024
MAX_DEPTH = 96
MAX_NODES = 250_000
