"""Optional real-Chromium checks. Requires Playwright and an installed Chromium.

Runs generated HTML through set_content without network access. This validates
DOM behavior, downloads and layout; it is not a file:// navigation test. Missing
browser/dependencies fail explicitly rather than silently skipping the suite.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
import shutil
import unittest
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

if __package__:
    from .review_view import render_packet
    from .fixture import sample
    from .analyze import analyze
else:
    from review_view import render_packet
    from fixture import sample
    from analyze import analyze

BROWSER = None
SCREENSHOTS = None


def anchor(kind, value):
    return kind + '-' + value.encode('utf-8').hex()


class BrowserTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.engine = sync_playwright().start()
        cls.browser = cls.engine.chromium.launch(executable_path=BROWSER, headless=True,
                                                 args=['--no-sandbox'])
        print('Chromium ' + cls.browser.version + '; DOM loaded from exact generated bytes using set_content')

    @classmethod
    def tearDownClass(cls):
        cls.browser.close(); cls.engine.stop()

    def setUp(self):
        self.page = self.browser.new_page(viewport={'width':1440,'height':1100}, accept_downloads=True)
        self.errors = []; self.requests = []
        self.page.on('pageerror', lambda error: self.errors.append(str(error)))
        self.page.on('console', lambda message: self.errors.append(message.text) if message.type=='error' else None)
        self.page.on('request', lambda request: self.requests.append(request.url))
        self.load(sample())

    def tearDown(self):
        self.page.close()
        self.assertEqual(self.errors, [])
        self.assertEqual(self.requests, [], 'The viewer must not make network or file-source requests')

    def load(self, data):
        self.data=data
        self.raw=(json.dumps(data,ensure_ascii=False,indent=2)+'\n').encode()
        self.page.set_content(render_packet(self.raw))
        expect(self.page.locator("#visible")).to_contain_text("Visible:")

    def visible_actions(self):
        return self.page.locator('#action-list article:visible h3').all_text_contents()

    def download(self, control):
        with self.page.expect_download() as info: self.page.click(control)
        return Path(info.value.path()).read_bytes()

    def test_01_canonical_counts_and_all_anchor_targets(self):
        self.assertEqual(self.page.locator('#incident-list article:visible').count(), 3)
        self.assertEqual(len(self.visible_actions()), 6)
        self.assertIn('NOT UNIVERSITY FINDINGS', self.page.locator('#classification').inner_text())
        missing=self.page.evaluate("Array.from(document.querySelectorAll('a[href^=\"#\"]')).filter(a=>!document.getElementById(a.hash.slice(1))).map(a=>a.hash)")
        self.assertEqual(missing, [])
        if SCREENSHOTS: self.page.screenshot(path=str(SCREENSHOTS/'review-desktop.png'))

    def test_02_group_and_overdue_filters_keep_shared_action_once(self):
        self.page.select_option('#group','RIS');self.page.select_option('#state','overdue')
        self.assertEqual(self.page.locator('#incident-list article:visible').count(),1)
        titles=self.visible_actions()
        self.assertEqual(len(titles),2)
        self.assertTrue(titles[0].startswith('ACT-02'));self.assertTrue(titles[1].startswith('ACT-03'))
        self.assertEqual(self.page.locator('#stats .stat strong').all_text_contents(),['3','6','3','10'])

    def test_03_unresolved_and_overdue_have_different_meanings(self):
        self.page.select_option('#state','unresolved');self.assertEqual(len(self.visible_actions()),4)
        self.page.select_option('#state','overdue');self.assertEqual(len(self.visible_actions()),3)
        self.assertEqual(self.page.locator('#incident-list article:visible').count(),3)

    def test_04_replacement_link_reveals_unresolved_successor(self):
        self.page.select_option('#state','replacement_documented')
        self.page.locator('#'+anchor('action','ACT-04')+' a').filter(has_text='ACT-05').click()
        expect(self.page.locator("#state")).to_have_value("all")
        self.assertTrue(self.page.locator('#'+anchor('action','ACT-05')).is_visible())
        self.assertIn('open work', self.page.locator('#'+anchor('action','ACT-05')).inner_text())
        self.assertIn('Filters reset', self.page.locator('#visible').inner_text())

    def test_05_evidence_link_opens_exact_source(self):
        self.page.locator('#'+anchor('incident','INC-ESS-1')+' a').filter(has_text='EV-ESS').first.click()
        target=self.page.locator('#'+anchor('source','EV-ESS'))
        expect(target).to_have_attribute("open", "")
        self.assertEqual(target.get_attribute('open'),'')
        self.assertIn('Fictional Registration submission record',target.inner_text())

    def test_06_search_includes_referenced_source_excerpts(self):
        self.page.fill('#query','Fictional change C-17')
        self.assertEqual(len(self.visible_actions()),1)
        self.assertTrue(self.visible_actions()[0].startswith('ACT-01'))
        self.page.fill('#query','nothing matches this invented phrase')
        self.assertEqual(len(self.visible_actions()),0)
        self.assertTrue(self.page.locator('#no-actions').is_visible())
        self.assertEqual(self.page.locator('#source-list details').count(),10)

    def test_07_selection_export_retains_full_unmodified_report(self):
        self.page.select_option('#group','RIS');self.page.select_option('#state','overdue')
        saved=json.loads(self.download('#export-json'))
        self.assertEqual(saved['selection']['action_ids'],['ACT-02','ACT-03'])
        self.assertEqual(saved['source']['report'],analyze(self.data))
        self.assertEqual(len(saved['source']['report']['sources']),10)
        self.assertEqual(base64.b64decode(saved['source']['original_packet_base64']),self.raw)
        self.assertEqual(saved['source']['input_sha256'],hashlib.sha256(self.raw).hexdigest())

    def test_08_original_download_is_byte_exact(self):
        self.assertEqual(self.download('#export-input'),self.raw)

    def test_09_text_export_preserves_unknowns_and_scope(self):
        self.page.select_option('#group','IAM')
        text=self.download('#export-text').decode()
        self.assertIn('SYNTHETIC',text);self.assertIn('filtered view',text)
        interval_line=next(line for line in text.splitlines() if line.startswith('Intervals in minutes: '))
        self.assertIsNone(json.loads(interval_line.split(': ',1)[1])['impact_to_restoration'])
        self.assertIn('ACT-05 / open_work',text)
        self.assertIn('Role: UNKNOWN',text)
        self.assertNotIn('ACT-01 /',text)

    def test_10_untrusted_text_is_plain_text_and_never_loaded(self):
        data=sample();marker='<img src="https://example.invalid/record" onerror="window.viewerProbe=1">'
        data['sources'][0]['excerpt']=marker
        data['sources'][0]['locator']='javascript:window.viewerProbe=2'
        data['incidents'][0]['service']='</script><script>window.viewerProbe=3</script>'
        self.load(data)
        target=self.page.locator('#'+anchor('source','EV-QUEUE'));target.locator('summary').click()
        self.assertEqual(target.locator('blockquote').inner_text(),marker)
        self.assertEqual(self.page.locator('img').count(),0)
        self.assertIsNone(self.page.evaluate('window.viewerProbe'))
        self.assertEqual(self.page.locator('a[href^="javascript:"]').count(),0)

    def test_11_mobile_and_keyboard_controls(self):
        self.page.set_viewport_size({'width':390,'height':844})
        self.assertFalse(self.page.evaluate('document.documentElement.scrollWidth > innerWidth'))
        self.page.get_by_role('combobox',name='Group',exact=True).select_option('IAM')
        self.page.get_by_role('button',name='Reset view',exact=True).focus();self.page.keyboard.press('Enter')
        self.assertEqual(self.page.locator('#group').input_value(),'all')
        self.assertEqual(len(self.visible_actions()),6)
        self.page.evaluate('scrollTo(0,0)')
        if SCREENSHOTS:self.page.screenshot(path=str(SCREENSHOTS/'review-mobile.png'))

    def test_12_print_expands_details_and_restores_ui(self):
        self.page.select_option('#group','RIS')
        before=self.page.locator('details:not([open])').count()
        self.page.evaluate("dispatchEvent(new Event('beforeprint'))")
        self.assertEqual(self.page.locator('details:not([open])').count(),0)
        self.page.emulate_media(media='print')
        self.assertFalse(self.page.locator('.controls').is_visible())
        self.page.emulate_media(media='screen')
        self.page.evaluate("dispatchEvent(new Event('afterprint'))")
        self.assertEqual(self.page.locator('details:not([open])').count(),before)
        self.assertEqual(self.page.locator('#group').input_value(),'RIS')

    def test_13_empty_packet_renders_explicit_no_records(self):
        data=sample()
        for key in ('incidents','actions','conditions','sources'): data[key]=[]
        self.load(data)
        self.assertTrue(self.page.locator('#no-incidents').is_visible())
        self.assertTrue(self.page.locator('#no-actions').is_visible())
        self.assertEqual(self.page.locator('#stats .stat strong').all_text_contents(),['0','0','0','0'])

    def test_14_engagement_label_and_no_external_links(self):
        data=sample();data['classification']='engagement';self.load(data)
        self.assertIn('ENGAGEMENT RECORDS',self.page.locator('#classification').inner_text())
        self.assertEqual(self.page.locator('a[href^="https:"],a[href^="http:"],a[href^="file:"]').count(),0)


if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--browser',default=shutil.which('chromium') or shutil.which('chromium-browser'))
    parser.add_argument('--screenshots',type=Path)
    args=parser.parse_args()
    if not args.browser:parser.error('Supply an installed Chromium executable with --browser')
    BROWSER=args.browser;SCREENSHOTS=args.screenshots
    if SCREENSHOTS:SCREENSHOTS.mkdir(parents=True,exist_ok=True)
    unittest.main(argv=['review_view_browser_test.py'],verbosity=2)
