#!/usr/bin/env python3
"""CLI for the fiction-labeling screen.

    python3 label_scan.py --root /path/to/revenue --lane-prefix uiowa_rfq_18649 \
        --output-dir examples/live_snapshot

Exit codes:
    0  nothing record-shaped is missing a label
    1  at least one record-shaped artifact is unlabeled or its label is buried
    2  the scan could not run
"""
from __future__ import annotations

import argparse
import csv
import io
import json
import os
import sys

import labelcheck
from labelcheck import (
    DISCLOSED, LABEL_BURIED, NOT_EVIDENCE, UNLABELED_CONFIG_SHAPED,
    UNDISCLOSED_PROVENANCE, UNREADABLE,
)

DISCLAIMER = (
    "This screen reports whether an artifact DISCLOSES that it is invented. It "
    "cannot tell whether the content is in fact synthetic, and it does not "
    "assert that any file contains a real University finding. Shape "
    "classification is heuristic. No lane is scored or marked compliant."
)

CSV_COLUMNS = ["provenance", "lane", "path", "status", "shape",
               "label_offset", "reason"]

# The screen flagged this tool's own CSV output for stating nothing about what
# it is. A column travels with the file; a sibling README does not.
CSV_PROVENANCE = ("REAL - generated by label_scan.py from committed source; "
                  "not synthetic")


def write_output(output_dir: str, relative_path: str, text: str) -> str:
    """The only writer. Refuses any target outside output_dir."""
    if os.path.isabs(relative_path):
        raise ValueError(f"refusing absolute output path {relative_path!r}")
    root = os.path.realpath(output_dir)
    target = os.path.realpath(os.path.join(root, relative_path))
    if target != root and not target.startswith(root + os.sep):
        raise ValueError(f"refusing to write outside the output directory: {relative_path!r}")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    return target


def render_csv(results: list) -> str:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=CSV_COLUMNS, lineterminator="\n")
    writer.writeheader()
    for r in results:
        row = dict(r.to_json(), provenance=CSV_PROVENANCE)
        writer.writerow({k: ("" if row.get(k) is None else row[k]) for k in CSV_COLUMNS})
    return buf.getvalue()


def render_markdown(results: list, summary: dict, root: str) -> str:
    lines = [
        "# Fiction-labeling screen",
        "",
        f"> {DISCLAIMER}",
        "",
        f"Scanned: `{root}`",
        "",
        f"- artifacts examined: **{summary['artifacts_examined']}**",
        f"- record-shaped artifacts missing a visible label: "
        f"**{summary['needs_a_label']}** across "
        f"**{len(summary['lanes_needing_a_label'])}** lane(s)",
        "",
        "| status | artifacts |",
        "| --- | --- |",
    ]
    for status, count in summary["by_status"].items():
        lines.append(f"| `{status}` | {count} |")
    lines += [
        "",
        "`UNLABELED_CONFIG_SHAPED` is listed but is **not** a finding: schema, "
        "vocabulary and weight files present no records and need no fiction "
        "label. Counting them would overstate the problem.",
        "",
    ]

    for status, heading, note in (
        (UNDISCLOSED_PROVENANCE,
         "UNDISCLOSED_PROVENANCE - the finding",
         "These carry assessment records or state results about the engagement's "
         "subjects, and the file says nowhere whether those contents are "
         "synthetic or real. A reader who opens one alone has no way to know. "
         "The remedy is a provenance statement, NOT necessarily a fiction "
         "label: a real measurement must not be labelled synthetic."),
        (LABEL_BURIED,
         "LABEL_BURIED - disclosed, but not where anyone will see it",
         "A disclosure exists but sits past the opening of the file. Its own "
         "class rather than a pass: a reader is not protected by a note further "
         "down than they read."),
    ):
        rows = [r for r in results if r.status == status]
        lines += ["", f"## {heading}", "", note, ""]
        if not rows:
            lines.append("None.")
            continue
        lines += ["| lane | artifact | shape | why |", "| --- | --- | --- | --- |"]
        for r in rows:
            lines.append(
                f"| `{r.lane}` | `{os.path.relpath(r.path, r.lane) if r.path.startswith(r.lane) else r.path}` "
                f"| {r.shape} | {r.reason} |"
            )

    lines += ["", "## Lanes with something to look at", ""]
    if not summary["lanes_needing_a_label"]:
        lines.append("None.")
    else:
        lines += ["| lane | artifacts needing a label |", "| --- | --- |"]
        counts = {}
        for r in results:
            if r.status in (UNDISCLOSED_PROVENANCE, LABEL_BURIED):
                counts[r.lane] = counts.get(r.lane, 0) + 1
        for lane in sorted(counts, key=lambda k: (-counts[k], k)):
            lines.append(f"| `{lane}` | {counts[lane]} |")

    unreadable = [r for r in results if r.status == UNREADABLE]
    lines += ["", "## Artifacts the screen could not read", ""]
    lines.append("None." if not unreadable else "")
    for r in unreadable:
        lines.append(f"- `{r.lane}/{r.path}` - {r.reason}")
    lines += [
        "",
        "An unreadable artifact is never counted as labeled.",
        "",
    ]
    return "\n".join(lines) + "\n"


def run(args) -> int:
    if not os.path.isdir(args.root):
        print(f"ERROR: not a directory: {args.root}", file=sys.stderr)
        return 2
    results = labelcheck.scan_tree(args.root, args.lane_prefix, args.header_bytes)
    summary = labelcheck.summarize(results)

    write_output(args.output_dir, "FICTION_LABELING_SCREEN.md",
                 render_markdown(results, summary, os.path.abspath(args.root)))
    write_output(args.output_dir, "artifacts.csv", render_csv(results))
    write_output(args.output_dir, "screen.json", json.dumps({
        "disclaimer": DISCLAIMER,
        "root": os.path.abspath(args.root),
        "header_bytes": args.header_bytes,
        "summary": summary,
        "artifacts": [r.to_json() for r in results],
    }, indent=2, sort_keys=True) + "\n")

    print(f"root            {os.path.abspath(args.root)}")
    print(f"artifacts       {summary['artifacts_examined']}")
    for status in (UNDISCLOSED_PROVENANCE, LABEL_BURIED, UNREADABLE,
                   UNLABELED_CONFIG_SHAPED, DISCLOSED, NOT_EVIDENCE):
        count = summary["by_status"].get(status)
        if count:
            print(f"  {status:<26} {count}")
    print()
    print(f"needs a label   {summary['needs_a_label']} artifact(s) across "
          f"{len(summary['lanes_needing_a_label'])} lane(s)")
    for r in results:
        if r.status == UNDISCLOSED_PROVENANCE:
            print(f"  UNLABELED  {r.path}")
    print()
    print(f"wrote           3 file(s) under {os.path.abspath(args.output_dir)}")
    return 1 if summary["needs_a_label"] else 0


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--root", required=True, help="directory to scan (read-only)")
    p.add_argument("--lane-prefix", default="")
    p.add_argument("--output-dir", default="examples")
    p.add_argument("--header-bytes", type=int, default=labelcheck.DEFAULT_HEADER_BYTES,
                   help="how far into a file a disclosure still counts as visible")
    args = p.parse_args(argv)
    try:
        return run(args)
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
