#!/usr/bin/env python3
"""host/sdc_multimodal.py — TEST FILE (owner 07-16): the SDC writes MULTIPLE locations, MULTIPLE modalities.

Owner's idea: what if the SDC wrote to multiple locations outside itself, in different generative modalities? The
addressing mechanism (address -> stored circuit -> generated output) is modality-agnostic: point the output wires at
amplitude (audio), a character code (text), or color (image, see sdc_render.py) and the SAME mechanism generates each.
This generates AUDIO (a stored triangle-wave shaper: phase -> amplitude) and TEXT (a stored circuit: index -> character)
by addressing stored circuits, and writes them to SEPARATE external files simultaneously. Image is sdc_render.py; together
they show one substrate driving multiple external sinks in multiple modalities. Stdlib only (wave module), no deps.

  python host/sdc_multimodal.py     # generate a WAV tone + a text file from stored circuits, to the desktop
"""
import os, sys, wave, struct
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
sys.stdout.reconfigure(encoding="utf-8")
import titan_circuit as TC

DESK = "C:/Users/lucys/OneDrive/Desktop"


def build_audio():
    """phase:8 -> amplitude:8 (triangle wave shaper, all gates). amp = phase<128 ? 2*phase : 2*(255-phase)."""
    c = TC.Circuit(8); p = c.IN
    amp = [c.C0] + [c.mux(p[7], p[k - 1], c.not_(p[k - 1])) for k in range(1, 8)]   # <<1, folded by the top bit
    TC.store("mm_audio", c, amp)


def build_text():
    """index:5 -> character code:8 (index + 'A'), all gates -> generates the alphabet by addressing."""
    c = TC.Circuit(5)
    x = c.IN + [c.C0, c.C0, c.C0]                              # zero-extend 5 -> 8
    A = c.cvec(65, 8); out = []; carry = c.C0                  # add constant 65 ('A')
    for i in range(8):
        axb = c.xor(x[i], A[i]); out.append(c.xor(axb, carry)); carry = c.or_(c.and_(x[i], A[i]), c.and_(axb, carry))
    TC.store("mm_text", c, out)


def gen(name, inbits, n_in):
    cd = TC.load(name); v = [0] * cd["n_wire"]; v[1] = 1
    for j in range(n_in): v[2 + j] = (inbits >> j) & 1
    ga, gb = cd["ga"], cd["gb"]
    for i in range(len(ga)): v[2 + n_in + i] = 1 - (v[ga[i]] & v[gb[i]])
    return sum((0 if o == 0 else 1 if o == 1 else v[o]) << k for k, o in enumerate(cd["outs"]))


if __name__ == "__main__":
    build_audio(); build_text()
    print("SDC MULTIMODAL — one substrate, multiple modalities, multiple external sinks.\n", flush=True)

    # AUDIO: a 440-ish Hz triangle tone at 8000 Hz, 1.0 s. phase accumulator is external state; the SHAPE is the circuit.
    rate = 8000; secs = 1.0; step = 14                         # phase step per sample -> pitch
    frames = bytearray(); phase = 0
    for i in range(int(rate * secs)):
        amp = gen("mm_audio", phase & 0xff, 8)                 # stored circuit shapes phase -> amplitude
        frames += struct.pack("<h", (amp - 128) * 200)        # center + scale to int16
        phase = (phase + step) & 0xff
    wav = os.path.join(DESK, "SDC_tone.wav")
    with wave.open(wav, "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(rate); w.writeframes(bytes(frames))
    print(f"  AUDIO  -> {os.path.basename(wav)}  ({len(frames)//2:,} samples, triangle tone generated by the stored shaper)", flush=True)

    # TEXT: generate the alphabet by addressing the stored index->char circuit
    txt = "".join(chr(gen("mm_text", i, 5)) for i in range(26))
    tpath = os.path.join(DESK, "SDC_text.txt")
    open(tpath, "w").write("generated by addressing a stored circuit (index -> character):\n" + txt + "\n")
    print(f"  TEXT   -> {os.path.basename(tpath)}  (\"{txt}\" generated by the stored index->char circuit)", flush=True)

    print(f"\n  two modalities (audio, text) from two stored circuits, written to two external sinks at once.", flush=True)
    print(f"  same addressing mechanism as the image render (sdc_render.py) and the numeric outputs — modality-agnostic.", flush=True)
