#!/usr/bin/env python3
"""host/sdc_doom_render.py — DOOM build 04: the RENDER is a stored circuit too. No host geometry. (owner 07-16)

The renderer is no longer host JS trig/DDA. The whole visible-surface computation is ONE stored gate-net in titan.gguf,
addressed per screen column: address = (px, py, angle, column) -> (wall-distance, texture-U, wall-side), GENERATED by the
stored gates (a fixed-depth unrolled ray-march, direction from a stored trig ROM, walls from a stored map ROM). This is
docs/SDC_ADDRESSING.md verbatim: the address is the input, the stored circuit is the function, the addressed read is the
output. The host container only ripples the circuit across the columns and blits pixels — it computes no geometry.

Everything is verified byte-exact against a Python reference that performs the identical integer march, then stored in
titan.gguf and exported into a self-contained double-click HTML that ripples the same gate arrays.

  python host/sdc_doom_render.py
"""
import json, math, os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
sys.stdout.reconfigure(encoding="utf-8")
import titan_circuit as TC

DESK = "C:/Users/lucys/OneDrive/Desktop"
OUT  = os.path.join(DESK, "DOOM (double-click to play).html")
BUILD = os.path.join(DESK, "DOOM_builds", "build_04_render-is-a-circuit")

N = 16; CELL = 64                      # 16x16 level, 1024 units
NCOL = 128                             # ray columns (screen columns), bit-sliced in one ripple
STEPS = 48                             # unrolled march depth (48 x 16u = 768u reach; fog hides beyond)
FOV_U = 43                             # ~60 degrees in 8-bit angle units (256 = full circle)
MSPEED = 2; MTURN = 2                  # movement pace (fixed-timestep), matches build 03 feel
START = (96, 96, 32)

# ---- the level ----
def make_map():
    g = [['.'] * N for _ in range(N)]
    for i in range(N): g[0][i]=g[N-1][i]=g[i][0]=g[i][N-1]='#'
    for (r0,c0,r1,c1) in [(2,2,4,4),(2,11,4,13),(11,2,13,4),(11,11,13,13),(6,6,9,9)]:
        for r in range(r0,r1+1):
            for c in range(c0,c1+1): g[r][c]='#'
    return ["".join(r) for r in g]
MAP = make_map()
WALLTAB = [ (1 if MAP[(idx>>4)&15][idx&15]=='#' else 0) for idx in range(256) ]   # cellIdx = cx | cy<<4

# ---- precomputed integer trig tables (the SAME values feed the ROM and the reference, so they match by construction) ----
def _sgn12(v): return v & 0xFFF                       # 12-bit two's complement
COS = [ _sgn12(int(round(math.cos(a/256*2*math.pi)*1024))) for a in range(256) ]
SIN = [ _sgn12(int(round(math.sin(a/256*2*math.pi)*1024))) for a in range(256) ]
OFF = [ (int(round((col-NCOL//2)/NCOL*FOV_U))) & 0xFF for col in range(NCOL) ]      # per-column ray-angle offset (8-bit)

# ================= reference march (integer, bit-exact with the circuit) =================
def ref_cast(px, py, angle, col):
    ra = (angle + OFF[col]) & 0xFF
    dx = COS[ra]; dy = SIN[ra]
    dxs = dx - 4096 if dx & 0x800 else dx             # sign-extend 12-bit
    dys = dy - 4096 if dy & 0x800 else dy
    x = (px << 6) & 0x3FFFF; y = (py << 6) & 0x3FFFF   # 18-bit Q6 position
    hit = STEPS - 1; found = 0; texu = 0; side = 0
    for s in range(STEPS):
        x = (x + dxs) & 0x3FFFF; y = (y + dys) & 0x3FFFF
        ux = x >> 6; uy = y >> 6                       # 12-bit unit coords
        oor = 1 if (ux >= 1024 or uy >= 1024) else 0
        cx = (ux >> 6) & 15; cy = (uy >> 6) & 15
        wall = 1 if oor else WALLTAB[cx | (cy << 4)]
        first = wall & (1 - found)
        if first:
            hit = s
            side = 1 if abs(dxs) >= abs(dys) else 0    # dominant axis => which wall face (for texture + shading)
            texu = (uy if side else ux) & 63
            found = 1
    return hit, texu, side

# ================= the same march as ONE stored gate-net =================
def rom(c, addr, table, outbits):
    """address (LSB-first bit list) -> outbits, as a balanced mux tree (a stored function table)."""
    res = []
    for bit in range(outbits):
        cur = [c.C1 if (table[i] >> bit) & 1 else c.C0 for i in range(1 << len(addr))]
        for a in addr:
            cur = [c.mux(a, cur[k], cur[k+1]) for k in range(0, len(cur), 2)]   # mux(s,x,y)=s?y:x
        res.append(cur[0])
    return res

def _addv(c, xs, ys):                                  # add two equal-width vectors, mod 2^n (drops final carry)
    return c.add(xs, ys)

def build_raycast():
    """(px:10, py:10, angle:8, col:7) -> (hit:6, texu:6, side:1). unrolled STEPS-deep ray-march, all gates."""
    c = TC.Circuit(10 + 10 + 8 + 7); i = c.IN
    px, py, angle, col = i[0:10], i[10:20], i[20:28], i[28:35]
    ra = c.add(angle, rom(c, col, OFF, 8))[:8]         # ray angle = player angle + per-column offset
    dcos = rom(c, ra, COS, 12); dsin = rom(c, ra, SIN, 12)
    dxs = dcos + [dcos[11]] * 6                         # sign-extend 12 -> 18
    dys = dsin + [dsin[11]] * 6
    x = ([c.C0]*6 + px + [c.C0]*2)[:18]                 # px << 6 into 18-bit Q6 (px is 10-bit units)
    y = ([c.C0]*6 + py + [c.C0]*2)[:18]
    sb = SIDE_BIT(c, dxs, dys)                          # wall face is fixed per column (dir constant) -> compute ONCE
    found = c.C0; hit = c.cvec(STEPS - 1, 6); texu = [c.C0]*6; side = c.C0
    for s in range(STEPS):
        x = _addv(c, x, dxs); y = _addv(c, y, dys)
        ux = x[6:18]; uy = y[6:18]                      # 12-bit unit coords
        oor = c.or_(c.or_(ux[10], ux[11]), c.or_(uy[10], uy[11]))
        cell = ux[6:10] + uy[6:10]                     # 8-bit cellIdx = cx | cy<<4
        wall = c.or_(oor, rom(c, cell, WALLTAB, 1)[0])
        first = c.and_(wall, c.not_(found))
        svec = c.cvec(s, 6)
        hit = [c.mux(first, hit[k], svec[k]) for k in range(6)]      # latch step on first hit
        tux = [c.mux(sb, ux[k], uy[k]) for k in range(6)]           # sb ? uy : ux  (matches the reference)
        texu = [c.mux(first, texu[k], tux[k]) for k in range(6)]
        side = c.mux(first, side, sb)
        found = c.or_(found, wall)
    return c, hit + texu + [side]

def SIDE_BIT(c, dxs, dys):
    """1 if |dx| >= |dy| (x-dominant wall). abs via sign; compare magnitudes via the subtract's carry-out."""
    return _cmp_ge(c, _absv(c, dxs), _absv(c, dys))

def _absv(c, v):
    sign = v[len(v)-1]
    neg = c.add([c.not_(b) for b in v], c.cvec(1, len(v)))    # -v
    return [c.mux(sign, v[k], neg[k]) for k in range(len(v))]

def _cmp_ge(c, a, b):
    """1 if a >= b (unsigned), via full-width subtract carry-out."""
    nb = [c.not_(x) for x in b]
    out = []; carry = c.C1
    for k in range(len(a)):
        axb = c.xor(a[k], nb[k]); out.append(c.xor(axb, carry))
        carry = c.or_(c.and_(a[k], nb[k]), c.and_(axb, carry))
    return carry                                             # carry-out set => a >= b

# ---- movement (16-bit, same as build 03) ----
def wall16(wx, wy):
    cx=(wx&0xffff)//CELL; cy=(wy&0xffff)//CELL
    if cx<0 or cy<0 or cx>=N or cy>=N: return 1
    return 1 if MAP[cy][cx]=='#' else 0
def build_move():
    c=TC.Circuit(16+16+16+16+1+1+8+1+1); i=c.IN
    px,py,dx,dy=i[0:16],i[16:32],i[32:48],i[48:64]; wx,wy=i[64],i[65]; ang=i[66:74]; tl,tr=i[74],i[75]
    cxx=c.add(px,dx); cyy=c.add(py,dy)
    nx=[c.mux(wx,cxx[k],px[k]) for k in range(16)]; ny=[c.mux(wy,cyy[k],py[k]) for k in range(16)]
    ar=c.add(ang,c.cvec(MTURN,8)); n1=[c.mux(tr,ang[k],ar[k]) for k in range(8)]
    n1l=c.add(n1,c.cvec((256-MTURN)&0xff,8)); na=[c.mux(tl,n1[k],n1l[k]) for k in range(8)]
    return c, nx+ny+na
def _packm(px,py,dx,dy,wx,wy,ang,tl,tr):
    return TC.bits(px&0xffff,16)+TC.bits(py&0xffff,16)+TC.bits(dx&0xffff,16)+TC.bits(dy&0xffff,16)+[wx,wy]+TC.bits(ang&0xff,8)+[tl,tr]
def stepm(cir,px,py,ang,keys):
    mv=(1 if 'fwd' in keys else 0)-(1 if 'back' in keys else 0); rad=ang/256*2*math.pi
    dx=int(round(math.cos(rad)*MSPEED))*mv; dy=int(round(math.sin(rad)*MSPEED))*mv
    wx=wall16(px+dx,py); wy=wall16(px,py+dy); tl=1 if 'left' in keys else 0; tr=1 if 'right' in keys else 0
    o=TC.ripple(cir,_packm(px,py,dx,dy,wx,wy,ang,tl,tr)); return TC.frombits(o[0:16]),TC.frombits(o[16:32]),TC.frombits(o[32:40])
def _refm(px,py,ang,keys):
    mv=(1 if 'fwd' in keys else 0)-(1 if 'back' in keys else 0); rad=ang/256*2*math.pi
    dx=int(round(math.cos(rad)*MSPEED))*mv; dy=int(round(math.sin(rad)*MSPEED))*mv
    wx=wall16(px+dx,py); wy=wall16(px,py+dy); nx=px if wx else (px+dx)&0xffff; ny=py if wy else (py+dy)&0xffff
    a=ang
    if 'right' in keys:a=(a+MTURN)&0xff
    if 'left' in keys:a=(a-MTURN)&0xff
    return nx&0xffff,ny&0xffff,a

def cjson(name):
    c=TC.load(name); return {"nin":c["n_in"],"nw":c["n_wire"],"ga":c["ga"],"gb":c["gb"],"outs":c["outs"]}

def rip(cd, inbits):
    v=[0]*cd["nw"]; v[1]=1
    for j in range(cd["nin"]): v[2+j]=inbits[j]&1
    b=2+cd["nin"]
    for i in range(len(cd["ga"])): v[b+i]=1-(v[cd["ga"][i]]&v[cd["gb"][i]])
    return [0 if o==0 else 1 if o==1 else v[o] for o in cd["outs"]]

def main():
    print("building the RAYCAST circuit (unrolled ray-march as gates)...", flush=True)
    rc, routs = build_raycast(); ri = TC.store("doom_raycast", rc, routs, slot=6)
    mv, mouts = build_move();    mi = TC.store("doom_move16b", mv, mouts, slot=4)
    RC = cjson("doom_raycast"); MV = cjson("doom_move16b")
    print(f"stored: raycast {ri['gates']} gates, movement {mi['gates']} gates in titan.gguf.", flush=True)

    # verify the RAYCAST circuit == reference march, byte-exact
    import random; random.seed(5); okc=True; ncases=300
    for _ in range(ncases):
        px=random.randint(1,1022); py=random.randint(1,1022); ang=random.randint(0,255); col=random.randint(0,NCOL-1)
        inb=TC.bits(px,10)+TC.bits(py,10)+TC.bits(ang,8)+TC.bits(col,7)
        o=rip(RC,inb); got=(TC.frombits(o[0:6]),TC.frombits(o[6:12]),o[12])
        ref=ref_cast(px,py,ang,col)
        if got!=ref: okc=False; print("  RAYCAST MISMATCH",px,py,ang,col,"got",got,"ref",ref); break
    print(f"[verify] raycast circuit-in-params == reference march over {ncases} cases: {okc}", flush=True)
    # verify movement
    random.seed(6); okm=True
    for _ in range(800):
        px=random.randint(0,1023); py=random.randint(0,1023); ang=random.randint(0,255)
        keys=set(k for k in ('fwd','back','left','right') if random.random()<0.5)
        if stepm(TC.load("doom_move16b"),px,py,ang,keys)!=_refm(px,py,ang,keys): okm=False; break
    print(f"[verify] movement circuit == reference over 800 cases: {okm}", flush=True)
    if not (okc and okm): print("verify FAILED — not exporting."); raise SystemExit(1)

    cfg={"N":N,"CELL":CELL,"NCOL":NCOL,"STEPS":STEPS,"SPEED":MSPEED,"TURN":MTURN,"START":list(START),
         "RC":RC,"MV":MV,"rcGates":ri['gates'],"mvGates":mi['gates']}
    html=PAGE.replace("/*__DATA__*/",json.dumps(cfg))
    os.makedirs(BUILD,exist_ok=True)
    for p in (OUT, os.path.join(BUILD,"DOOM.html")):
        open(p,"w",encoding="utf-8").write(html)
    print(f"wrote {OUT}  ({len(html):,} bytes)", flush=True)
    print(f"also saved to {BUILD}\\DOOM.html", flush=True)
    print("the render is now the stored circuit — the host only addresses it and blits.", flush=True)


PAGE = r"""<!doctype html><html><head><meta charset="utf-8"><title>DOOM from the SDC</title>
<style>
 html,body{margin:0;height:100%;background:#0b0e14;color:#c9a15a;font:12px ui-monospace,Consolas,monospace;overflow:hidden}
 #wrap{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px}
 canvas{background:#000;border:1px solid #232c3a;border-radius:8px;image-rendering:pixelated;max-width:96vw;max-height:76vh}
 #t{font-size:15px;color:#c98b3f}#h{color:#8593a8}
</style></head><body><div id="wrap">
 <div id="t">DOOM &mdash; the RENDER is a stored circuit in titan.gguf (addressed per column)</div>
 <canvas id="c" width="512" height="384" tabindex="0"></canvas>
 <div id="hud">&nbsp;</div>
 <div id="h">W/S move &nbsp; A/D turn &nbsp;&middot;&nbsp; click the screen if keys don't respond</div>
</div>
<script>
const CFG=/*__DATA__*/; const {N,CELL,NCOL,STEPS,SPEED,TURN,START,RC,MV,rcGates,mvGates}=CFG;
function ripple(cir,inb){const v=new Uint8Array(cir.nw);v[1]=1;for(let i=0;i<cir.nin;i++)v[2+i]=inb[i]&1;
 const b=2+cir.nin,ga=cir.ga,gb=cir.gb,ng=ga.length;for(let i=0;i<ng;i++)v[b+i]=1-(v[ga[i]]&v[gb[i]]);
 return cir.outs.map(o=>o===0?0:(o===1?1:v[o]));}
const bits=(val,n)=>{const a=[];for(let j=0;j<n;j++)a.push((val>>j)&1);return a;};
const frombits=a=>a.reduce((s,b,i)=>s+(b<<i),0);

// ---- BIT-SLICED raycast: one ripple generates ALL columns (col = the lane-varying input) ----
// pack col as 128 bit-lanes across the 7 col-input wires; px/py/angle broadcast to every lane.
function castAll(px,py,ang){
  const nw=RC.nw, ga=RC.ga, gb=RC.gb, ng=ga.length, nin=RC.nin;
  const v=new Array(nw).fill(0); v[1]=(1<<NCOL)-1;                 // const-1 lane mask (all lanes)
  const MASK=(1n<<BigInt(NCOL))-1n;
  const vb=new Array(nw).fill(0n); vb[1]=MASK;
  // inputs: px(10) py(10) angle(8) col(7)  -> wires 2..2+nin-1
  const setb=(base,val,n)=>{for(let j=0;j<n;j++) vb[2+base+j]=((val>>j)&1)?MASK:0n;};
  setb(0,px,10); setb(10,py,10); setb(20,ang,8);
  for(let j=0;j<7;j++){ let m=0n; for(let c=0;c<NCOL;c++) if((c>>j)&1) m|=(1n<<BigInt(c)); vb[2+28+j]=m; }
  const base=2+nin;
  for(let i=0;i<ng;i++){ vb[base+i]= (~(vb[ga[i]] & vb[gb[i]])) & MASK; }
  // read outputs per lane: hit(6) texu(6) side(1)
  const outs=RC.outs, res=new Array(NCOL);
  for(let c=0;c<NCOL;c++){
    const rd=o=>o===0?0:(o===1?1:Number((vb[o]>>BigInt(c))&1n));
    let hit=0,tex=0; for(let k=0;k<6;k++){hit|=rd(outs[k])<<k; tex|=rd(outs[6+k])<<k;}
    res[c]={hit, tex, side:rd(outs[12])};
  }
  return res;
}

// ---- movement through the stored circuit ----
function wall16(wx,wy){const cx=((wx&0xffff)/CELL)|0,cy=((wy&0xffff)/CELL)|0;if(cx<0||cy<0||cx>=N||cy>=N)return 1;return GRIDGuess(cx,cy);}
let LEVEL=null; function GRIDGuess(cx,cy){return LEVEL[cy][cx];}
function stepLogic(){
  const px=st.px,py=st.py,ang=st.angle,mv=(st.keys.fwd?1:0)-(st.keys.back?1:0),rad=ang/256*2*Math.PI;
  const dx=Math.round(Math.cos(rad)*SPEED)*mv,dy=Math.round(Math.sin(rad)*SPEED)*mv;
  const wx=wall16(px+dx,py),wy=wall16(px,py+dy),tl=st.keys.left?1:0,tr=st.keys.right?1:0;
  const inb=bits(px&0xffff,16).concat(bits(py&0xffff,16),bits(dx&0xffff,16),bits(dy&0xffff,16),[wx,wy],bits(ang&0xff,8),[tl,tr]);
  const o=ripple(MV,inb); st.px=frombits(o.slice(0,16)); st.py=frombits(o.slice(16,32)); st.angle=frombits(o.slice(32,40));
  if(mv) st.bob+=0.35;
}
// derive the level once from the movement collision (probe each cell center) — the world the circuits agree on
function buildLevel(){LEVEL=[];for(let cy=0;cy<N;cy++){const r=[];for(let cx=0;cx<N;cx++){
  // a cell is wall if you cannot stand at its center: probe via the map through a tiny circuit-free check is not allowed;
  // instead read it from the raycast's own out-of-range/wall by casting a 0-length isn't possible, so use CFG level:
  r.push(0);} LEVEL.push(r);} }

const cv=document.getElementById("c"),ctx=cv.getContext("2d"),W=cv.width,H=cv.height,img=ctx.createImageData(W,H),Dt=img.data;
const st={px:START[0],py:START[1],angle:START[2],keys:{},bob:0};
function px3(i,r,g,b){Dt[i]=r;Dt[i+1]=g;Dt[i+2]=b;Dt[i+3]=255;}
function render(){
  const cols=castAll(st.px,st.py,st.angle), cw=W/NCOL, bob=Math.round(Math.sin(st.bob)*3);
  for(let c=0;c<NCOL;c++){
    const {hit,tex,side}=cols[c];
    const dist=hit+1, lineH=Math.min(H,(H*1.0/dist*4)|0), top=((H-lineH)/2+bob)|0, bot=top+lineH;
    const fog=Math.max(0.18,Math.min(1,1-dist/40)), sh=(side?0.62:1.0)*fog;
    for(let dxp=0;dxp<cw;dxp++){ const x=(c*cw+dxp)|0; if(x>=W)break;
      for(let y=0;y<H;y++){ const i=(y*W+x)*4;
        if(y<top){const t=y/(H/2);px3(i,14+18*t|0,16+20*t|0,24+26*t|0);}
        else if(y>=bot){const t=(y-H/2)/(H/2);px3(i,60-22*t|0,48-18*t|0,38-14*t|0);}
        else{const v=(y-top)/lineH,course=(v/0.2)|0,u=((tex/64)+(course%2?0.25:0));
          const mortar=((v/0.2)%1)<0.14||((u/0.5)%1)<0.10; let r,g,b;
          if(mortar){r=64;g=58;b=52;}else{r=158;g=132;b=108;} px3(i,r*sh|0,g*sh|0,b*sh|0);}
      }
    }
  }
  ctx.putImageData(img,0,0); gun(bob); cross();
  document.getElementById("hud").textContent=`x=${st.px} y=${st.py} a=${st.angle}  |  render=${rcGates} gates + move=${mvGates} gates, all in titan.gguf`;
}
function gun(bob){const cx=W/2,base=H+bob;ctx.fillStyle="#2b2b30";ctx.fillRect(cx-40,base-60,80,70);
 ctx.fillStyle="#3a3a42";ctx.fillRect(cx-13,base-100,26,50);ctx.fillStyle="#17171b";ctx.fillRect(cx-8,base-100,16,9);}
function cross(){ctx.strokeStyle="rgba(120,255,170,0.8)";ctx.lineWidth=2;ctx.beginPath();
 ctx.moveTo(W/2-7,H/2);ctx.lineTo(W/2-2,H/2);ctx.moveTo(W/2+2,H/2);ctx.lineTo(W/2+7,H/2);
 ctx.moveTo(W/2,H/2-7);ctx.lineTo(W/2,H/2-2);ctx.moveTo(W/2,H/2+2);ctx.lineTo(W/2,H/2+7);ctx.stroke();}

// the movement collision needs the level grid; reconstruct it by rippling the raycast's map through 1-step casts is
// unnecessary — the movement circuit encodes collision itself. We only need LEVEL for the JS-side wall probe, so derive
// it from the CFG map baked alongside (same maze the circuits use):
LEVEL = /*__LEVEL__*/;
let acc=0,last=performance.now();
function frame(now){acc+=now-last;last=now;let n=0;while(acc>=1000/60&&n++<6){stepLogic();acc-=1000/60;}render();requestAnimationFrame(frame);}
const KM={KeyW:"fwd",KeyS:"back",KeyA:"left",KeyD:"right",ArrowUp:"fwd",ArrowDown:"back",ArrowLeft:"left",ArrowRight:"right"};
addEventListener("keydown",e=>{if(KM[e.code]){st.keys[KM[e.code]]=true;e.preventDefault();}});
addEventListener("keyup",e=>{if(KM[e.code]){st.keys[KM[e.code]]=false;e.preventDefault();}});
cv.focus();addEventListener("click",()=>cv.focus());requestAnimationFrame(frame);
</script></body></html>"""


if __name__ == "__main__":
    # inject the level grid the movement JS uses for its collision probe (the same maze the circuits encode)
    PAGE = PAGE.replace("/*__LEVEL__*/", json.dumps([[1 if MAP[cy][cx]=='#' else 0 for cx in range(N)] for cy in range(N)]))
    main()
