#!/usr/bin/env python3
"""host/sdc_render.py — TEST FILE (owner 07-16): the SDC RENDERS. A stored circuit outputs pixel color from (x,y).

Owner's idea: the SDC doesn't have to output numbers to be rendered — it can determine PIXEL COORDS + COLOR directly, so
it's a display. This stores a circuit that maps a pixel ADDRESS (x,y) -> RGB, then GENERATES an image by addressing every
pixel through the gates (never stored — generative computing, docs/SDC_ADDRESSING.md). The image is the SDC rendering: an
addressed read per pixel, color generated on power. Writes a PNG you can open (stdlib zlib, no deps).

  python host/sdc_render.py [W]     # generate a WxW image from the stored pixel-circuit -> sdc_render.png
"""
import os, struct, sys, time, zlib
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
sys.stdout.reconfigure(encoding="utf-8")
import titan_circuit as TC

OUT = os.path.join(HERE, "sdc_render.png")
BITS = 7                                                       # 2^7 = 128 px per axis


def build_pixel_circuit():
    """(x:7, y:7) -> 24-bit RGB, all gates. R = (x^y)<<1 (XOR texture), G = x&y, B = x|y — a stored, generative image."""
    c = TC.Circuit(2 * BITS); x = c.IN[0:BITS]; y = c.IN[BITS:2 * BITS]
    R = [c.C0] + [c.xor(x[k], y[k]) for k in range(BITS)]      # <<1
    G = [c.and_(x[k], y[k]) for k in range(BITS)] + [c.C0]
    B = [c.or_(x[k], y[k]) for k in range(BITS)] + [c.C0]
    TC.store("pix", c, R + G + B)


def render(W):
    cd = TC.load("pix"); n_in = 2 * BITS; ga, gb = cd["ga"], cd["gb"]; outs = cd["outs"]
    rows = []
    t0 = time.time()
    for y in range(W):
        row = bytearray()
        for x in range(W):
            addr = (x & ((1 << BITS) - 1)) | ((y & ((1 << BITS) - 1)) << BITS)   # the pixel ADDRESS
            v = [0] * cd["n_wire"]; v[1] = 1
            for j in range(n_in): v[2 + j] = (addr >> j) & 1
            for i in range(len(ga)): v[2 + n_in + i] = 1 - (v[ga[i]] & v[gb[i]])
            val = sum((0 if o == 0 else 1 if o == 1 else v[o]) << k for k, o in enumerate(outs))  # generated color
            row += bytes((val & 0xff, (val >> 8) & 0xff, (val >> 16) & 0xff))
        rows.append(bytes(row))
    dt = time.time() - t0
    # minimal PNG (RGB, 8-bit) — stdlib only
    raw = b"".join(b"\x00" + r for r in rows)
    def chunk(t, d): return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)
    png = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", W, W, 8, 2, 0, 0, 0)) +
           chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))
    with open(OUT, "wb") as f: f.write(png)
    return dt


if __name__ == "__main__":
    W = int(sys.argv[1]) if len(sys.argv) > 1 else 128
    build_pixel_circuit()
    cd = TC.load("pix")
    print(f"SDC RENDER — pixel circuit stored ({len(cd['ga'])} gates). generating {W}x{W} = {W*W:,} pixels by addressing ...", flush=True)
    dt = render(W)
    print(f"  rendered in {dt:.2f}s -> {OUT}  ({os.path.getsize(OUT):,} B PNG)", flush=True)
    print(f"  every pixel's color was GENERATED by addressing the stored gates (x,y -> RGB) — no image stored.", flush=True)
    print(f"  the SDC is a display: it output pixel coords + color directly. open the PNG to see it render.", flush=True)
