#!/usr/bin/env python3
"""host/sdc_generative.py — TEST FILE (owner 07-16): GENERATIVE COMPUTING — the table computes itself when addressed.

The addressing reframe, playable (docs/SDC_ADDRESSING.md). Functions are stored as gate-nets in titan.gguf's params; you
give an ADDRESS (an input) and the output is GENERATED by the stored gates on read — never stored, never precomputed. A
2^n-entry 'table' is a fixed ~KB circuit + on-read generation. `sweep` generates a whole virtual table in lockstep.

  python host/sdc_generative.py            # REPL. commands: add A B | mul A B | cipher X | sweep add|mul|cipher | quit
  (also reads piped commands, e.g.  echo "mul 12 11" | python host/sdc_generative.py)
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
sys.stdout.reconfigure(encoding="utf-8")
import titan_circuit as TC

PERM = [7, 2, 11, 0, 5, 9, 1, 8, 3, 10, 4, 6]; KCONST = 0xA5C


def _addN(c, xs, ys, n):
    out = []; carry = c.C0
    for i in range(n):
        xi = xs[i] if i < len(xs) else c.C0; yi = ys[i] if i < len(ys) else c.C0
        axb = c.xor(xi, yi); out.append(c.xor(axb, carry))
        carry = c.or_(c.and_(xi, yi), c.and_(axb, carry))
    out.append(carry); return out


def build_all():
    # ADD: 6-bit + 6-bit -> 7-bit (the addition table, generated)
    c = TC.Circuit(12); s = _addN(c, c.IN[0:6], c.IN[6:12], 6); TC.store("g_add", c, s)
    # MUL: 4-bit x 4-bit -> 8-bit (the multiplication table, generated)
    c = TC.Circuit(8); a, b = c.IN[0:4], c.IN[4:8]; acc = [c.C0] * 8
    for i in range(4):
        row = [c.C0] * 8
        for j in range(4): row[i + j] = c.and_(a[j], b[i])
        acc = _addN(c, acc, row, 8)[:8]
    TC.store("g_mul", c, acc)
    # CIPHER: 12-bit reversible scramble (a codec, generated)
    c = TC.Circuit(12); f = [c.xor(c.IN[PERM[j]], c.C1 if (KCONST >> j) & 1 else c.C0) for j in range(12)]
    TC.store("g_cipher", c, f)


def gen(name, inbits, n_in):
    cd = TC.load(name); v = [0] * cd["n_wire"]; v[1] = 1
    for j in range(n_in): v[2 + j] = (inbits >> j) & 1
    ga, gb = cd["ga"], cd["gb"]
    for i in range(len(ga)): v[2 + n_in + i] = 1 - (v[ga[i]] & v[gb[i]])
    val = 0
    for k, o in enumerate(cd["outs"]):
        val |= (0 if o == 0 else 1 if o == 1 else v[o]) << k
    return val


OPS = {"add": (12, lambda a, b: (a & 63) | ((b & 63) << 6)), "mul": (8, lambda a, b: (a & 15) | ((b & 15) << 4)),
       "cipher": (12, lambda a, b: a & 4095)}


def do(cmd):
    p = cmd.split()
    if not p: return True
    op = p[0].lower()
    if op in ("quit", "exit", "q"): return False
    if op == "help":
        print("  add A B | mul A B | cipher X | sweep add|mul|cipher | quit"); return True
    if op == "sweep" and len(p) > 1 and p[1] in OPS:
        name = "g_" + p[1]; n_in, _ = OPS[p[1]]; lim = min(16, 1 << (n_in // 2 if p[1] != "cipher" else 4))
        print(f"  generated table for '{p[1]}' (addressed into existence, never stored):")
        for a in range(lim):
            if p[1] == "cipher": print(f"    {a:#05x} -> {gen(name, a, n_in):#05x}")
            else: print(f"    {a} op {a} -> {gen(name, OPS[p[1]][1](a, a), n_in)}")
        return True
    if op in OPS:
        try:
            a = int(p[1], 0); b = int(p[2], 0) if len(p) > 2 else 0
        except Exception:
            print("  usage: add A B | mul A B | cipher X"); return True
        n_in, enc = OPS[op]; out = gen("g_" + op, enc(a, b), n_in)
        if op == "add": print(f"  {a} + {b} = {out}   (generated by the stored gates — no table stored)")
        elif op == "mul": print(f"  {a} x {b} = {out}   (the product, generated on read)")
        else: print(f"  cipher({a:#05x}) = {out:#05x}   (codec output, generated by addressing)")
        return True
    print("  ? type help"); return True


if __name__ == "__main__":
    build_all()
    print("GENERATIVE COMPUTING — stored circuits, outputs generated by addressing. type help, or quit.", flush=True)
    if not sys.stdin.isatty():                                 # piped commands
        for line in sys.stdin:
            if not do(line.strip()): break
    else:
        while True:
            try: line = input("addr> ")
            except (EOFError, KeyboardInterrupt): break
            if not do(line.strip()): break
    print("done.", flush=True)
