#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Emit a deterministic prefix-only child of one generated S13 route arm."""
from __future__ import annotations

import argparse
import ast
import base64
import hashlib
import json
from pathlib import Path
from typing import Any
import zlib

SCHEMA = "titan-v3-s13-prefix-route/v1"
REQUIRED = (
    "ARM_ID", "SOURCE_EPISODE", "SOURCE_TEAM", "SOURCE_SEAT",
    "SOURCE_REWARD", "SOURCE_SHA256", "TAPE_SHA256", "_PACKED",
)


class PrefixRouteError(RuntimeError):
    pass


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def literals(path: Path) -> dict[str, Any]:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, UnicodeError, SyntaxError) as exc:
        raise PrefixRouteError(f"cannot parse source arm: {exc}") from exc
    found: dict[str, Any] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name) or target.id not in REQUIRED:
            continue
        try:
            found[target.id] = ast.literal_eval(node.value)
        except (TypeError, ValueError, SyntaxError) as exc:
            raise PrefixRouteError(f"{target.id} must be a literal") from exc
    missing = [name for name in REQUIRED if name not in found]
    if missing:
        raise PrefixRouteError(f"source arm is missing literals: {missing!r}")
    return found


def decode_source_arm(
    path: Path, *, expected_python_sha256: str | None = None
) -> tuple[dict[str, Any], dict[str, dict[str, Any]]]:
    try:
        source = path.read_bytes()
    except OSError as exc:
        raise PrefixRouteError(f"cannot read source arm: {exc}") from exc
    python_sha = sha256(source)
    if expected_python_sha256 is not None and python_sha != expected_python_sha256:
        raise PrefixRouteError(
            f"source arm SHA-256 mismatch: expected={expected_python_sha256} actual={python_sha}"
        )
    meta = literals(path)
    if not isinstance(meta["_PACKED"], str) or not isinstance(meta["TAPE_SHA256"], str):
        raise PrefixRouteError("packed tape literals must be strings")
    try:
        raw = zlib.decompress(base64.b85decode(meta["_PACKED"].encode("ascii")))
    except (UnicodeEncodeError, ValueError, zlib.error) as exc:
        raise PrefixRouteError(f"cannot decode source tape: {exc}") from exc
    if sha256(raw) != meta["TAPE_SHA256"]:
        raise PrefixRouteError("source tape SHA-256 mismatch")
    try:
        tape = json.loads(raw.decode("utf-8"))
    except (UnicodeError, json.JSONDecodeError) as exc:
        raise PrefixRouteError(f"source tape is not valid JSON: {exc}") from exc
    if not isinstance(tape, dict) or not tape:
        raise PrefixRouteError("source tape must be a nonempty mapping")
    numbered: dict[int, dict[str, Any]] = {}
    for key, entry in tape.items():
        if (
            not isinstance(key, str)
            or not key.isdigit()
            or str(int(key)) != key
            or not isinstance(entry, dict)
            or int(key) in numbered
        ):
            raise PrefixRouteError("source tape has a noncanonical step or entry")
        numbered[int(key)] = entry
    maximum = max(numbered)
    if sorted(numbered) != list(range(maximum + 1)):
        raise PrefixRouteError("source tape must cover a contiguous zero-based route")
    meta = dict(meta, python_sha256=python_sha, tape_steps=maximum + 1)
    return meta, {str(step): numbered[step] for step in range(maximum + 1)}


def render(
    meta: dict[str, Any], tape: dict[str, dict[str, Any]], cutoff: int,
    runtime: Path, baseline: Path,
) -> tuple[str, bytes]:
    raw = json.dumps(tape, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()
    packed = base64.b85encode(zlib.compress(raw, 9)).decode("ascii")
    child_id = f"{meta['ARM_ID']}--prefix{cutoff}"
    source = f'''# SPDX-License-Identifier: Apache-2.0
# Deterministically generated by prefix_route.py; research arm, not canonical runtime.
from __future__ import annotations
import base64, hashlib, importlib.util, json, zlib

ARM_ID = {child_id!r}
PARENT_ARM_ID = {meta['ARM_ID']!r}
PREFIX_CUTOFF = {cutoff!r}
SOURCE_EPISODE = {meta['SOURCE_EPISODE']!r}
SOURCE_TEAM = {meta['SOURCE_TEAM']!r}
SOURCE_SEAT = {meta['SOURCE_SEAT']!r}
SOURCE_REWARD = {meta['SOURCE_REWARD']!r}
SOURCE_SHA256 = {meta['SOURCE_SHA256']!r}
PARENT_TAPE_SHA256 = {meta['TAPE_SHA256']!r}
TAPE_SHA256 = {sha256(raw)!r}
_PACKED = {packed!r}


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {{path}}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_runtime = _load("s13_prefix_runtime_" + hashlib.sha256(ARM_ID.encode()).hexdigest()[:12], {str(runtime)!r})
_baseline = _load("s13_prefix_baseline_" + hashlib.sha256(ARM_ID.encode()).hexdigest()[:12], {str(baseline)!r})
_raw = zlib.decompress(base64.b85decode(_PACKED.encode("ascii")))
if hashlib.sha256(_raw).hexdigest() != TAPE_SHA256:
    raise RuntimeError("embedded prefix tape digest mismatch")
_tape = json.loads(_raw.decode("utf-8"))
_policy = _runtime.LeaderRoutePolicy(_baseline.agent, _tape, mode="post24_full", start_step=24)


def agent(obs, configuration=None):
    return _policy.agent(obs, configuration)


def diagnostics():
    return _policy.diagnostics()
'''
    return source, raw


def build_prefix(
    *, source_arm: Path, runtime: Path, baseline_entry: Path, cutoff: int,
    output: Path, receipt: Path, expected_source_sha256: str | None = None,
) -> dict[str, Any]:
    meta, tape = decode_source_arm(source_arm, expected_python_sha256=expected_source_sha256)
    maximum = len(tape) - 1
    if type(cutoff) is not int or not 24 <= cutoff < maximum:
        raise PrefixRouteError(f"cutoff must be an integer in [24, {maximum - 1}]")
    if not runtime.is_file() or not baseline_entry.is_file():
        raise PrefixRouteError("runtime and baseline entry must exist")
    prefix = {str(step): tape[str(step)] for step in range(cutoff + 1)}
    rendered, raw = render(meta, prefix, cutoff, runtime.resolve(), baseline_entry.resolve())
    output.parent.mkdir(parents=True, exist_ok=True)
    receipt.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    result = {
        "schema": SCHEMA,
        "parent_arm_id": meta["ARM_ID"],
        "child_arm_id": f"{meta['ARM_ID']}--prefix{cutoff}",
        "source_arm": str(source_arm),
        "source_python_sha256": meta["python_sha256"],
        "source_tape_sha256": meta["TAPE_SHA256"],
        "source_steps": meta["tape_steps"],
        "cutoff": cutoff,
        "first_omitted_step": cutoff + 1,
        "retained_steps": cutoff + 1,
        "removed_steps": maximum - cutoff,
        "prefix_tape_sha256": sha256(raw),
        "output": str(output),
        "output_python_sha256": sha256(rendered.encode()),
        "runtime": str(runtime.resolve()),
        "baseline_entry": str(baseline_entry.resolve()),
        "handoff_contract": "baseline called every turn; first absent row permanently hands back",
    }
    receipt.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    build = sub.add_parser("build")
    for flag in ("source-arm", "runtime", "baseline-entry", "output", "receipt"):
        build.add_argument(f"--{flag}", type=Path, required=True)
    build.add_argument("--cutoff", type=int, required=True)
    build.add_argument("--expected-source-sha256")
    args = parser.parse_args(argv)
    result = build_prefix(
        source_arm=args.source_arm,
        runtime=args.runtime,
        baseline_entry=args.baseline_entry,
        cutoff=args.cutoff,
        output=args.output,
        receipt=args.receipt,
        expected_source_sha256=args.expected_source_sha256,
    )
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
