#!/usr/bin/env python3
"""OPS-PERF-SCAN -- run the hotspot scan across every delivered UIOWA lane.

Read-only. Reads other seats' lanes and writes nothing into them; all output
goes to the directory given by --out.

Usage:
    python3 scan_kit.py --revenue /path/to/commons/revenue --out results
"""
from __future__ import annotations

import argparse
import json
import platform
import sys
import time
from pathlib import Path

import scan_hotspots as sh

DEFAULT_LANE_GLOB = "uiowa_rfq_18649_*"


def scan_kit(revenue_root: Path, lane_glob: str = DEFAULT_LANE_GLOB) -> dict:
    revenue_root = Path(revenue_root).resolve()
    lanes = sorted(p for p in revenue_root.glob(lane_glob) if p.is_dir())
    findings, unscannable, lane_names = [], [], []
    files_scanned = 0
    t0 = time.perf_counter()
    for lane in lanes:
        report = sh.scan_tree(lane)
        lane_names.append(lane.name)
        files_scanned += report["files_scanned"]
        for f in report["findings"]:
            f["file"] = f"{lane.name}/{f['file']}"
            findings.append(f)
        for u in report["unscannable"]:
            u["file"] = f"{lane.name}/{u['file']}"
            unscannable.append(u)
    elapsed = time.perf_counter() - t0

    by_pattern = {}
    for f in findings:
        by_pattern[f["pattern"]] = by_pattern.get(f["pattern"], 0) + 1

    return {
        "schema": "uiowa-ops-perf-scan-kit-v1",
        "revenue_root": str(revenue_root),
        "lane_glob": lane_glob,
        "lanes_scanned": len(lanes),
        "lane_names": lane_names,
        "files_scanned": files_scanned,
        "files_unscannable": len(unscannable),
        "unscannable": unscannable,
        "finding_count": len(findings),
        "findings_by_pattern": by_pattern,
        "findings": findings,
        "scan_seconds": elapsed,
        "environment": {
            "python_version": sys.version.split()[0],
            "platform": platform.platform(),
            "scanned_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        },
        "disclaimer": sh.scan_tree.__doc__ and (
            "Structural matches, not proven defects. CONFIRMED_SHAPE means the code really "
            "has the shape described; whether it costs anything depends on input sizes this "
            "scanner cannot see. measured_cost is a real figure ONLY where UIOWA-095 measured "
            "that pattern. This is not a score of any lane, seat or person."
        ),
    }


def render(report: dict) -> str:
    env = report["environment"]
    lines = [
        "# Delivery-kit performance hotspot scan",
        "",
        "Read-only AST scan of every delivered UIOWA lane, looking for the two performance",
        "shapes measured under UIOWA-095 plus two related ones. Generated by `scan_kit.py`.",
        "",
        "**Structural matches, not proven defects. This is not a score.** Findings are listed",
        "by file so an owner can act on their own code. No lane, seat or person is ranked and",
        "no quality metric is computed. `measured_cost` is a real figure only where UIOWA-095",
        "actually measured that pattern; everywhere else it is UNKNOWN.",
        "",
        f"- Lanes scanned: **{report['lanes_scanned']}**",
        f"- Python files scanned: **{report['files_scanned']}**",
        f"- Files that could NOT be scanned: **{report['files_unscannable']}** (never counted as clean)",
        f"- Structural matches: **{report['finding_count']}**",
        f"- Scan time: {report['scan_seconds']:.2f} s on {env['platform']}, Python {env['python_version']}",
        f"- Scanned at: {env['scanned_at_utc']}",
        "",
        "## Matches by pattern",
        "",
        "| Pattern | Count | Cost evidence |",
        "| --- | ---: | --- |",
    ]
    for pattern, count in sorted(report["findings_by_pattern"].items()):
        ev = sh.MEASURED_EVIDENCE.get(pattern)
        cost = f"measured under UIOWA-095 — {ev['result']}" if ev else "UNKNOWN — not measured"
        lines.append(f"| `{pattern}` | {count} | {cost} |")
    if not report["findings_by_pattern"]:
        lines.append("| _none_ | 0 | — |")

    lines += ["", "## Findings", "",
              "| File | Line | Pattern | Confidence | Source |",
              "| --- | ---: | --- | --- | --- |"]
    for f in sorted(report["findings"], key=lambda x: (x["pattern"], x["file"], x["line"])):
        src = f["source"].replace("|", "\\|")
        lines.append(f"| `{f['file']}` | {f['line']} | `{f['pattern']}` | {f['confidence']} | `{src}` |")

    if report["unscannable"]:
        lines += ["", "## Could not be scanned", "",
                  "| File | Reason |", "| --- | --- |"]
        for u in report["unscannable"]:
            lines.append(f"| `{u['file']}` | {u['reason']} |")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Scan every delivered UIOWA lane (read-only).")
    p.add_argument("--revenue", type=Path, required=True, help="Path to the repo's revenue/ directory.")
    p.add_argument("--lane-glob", default=DEFAULT_LANE_GLOB)
    p.add_argument("--out", type=Path, default=None)
    a = p.parse_args(argv)

    if not a.revenue.is_dir():
        print(f"not a directory: {a.revenue}", file=sys.stderr)
        return 2

    report = scan_kit(a.revenue, a.lane_glob)
    if a.out:
        a.out.mkdir(parents=True, exist_ok=True)
        (a.out / "kit_scan_results.json").write_text(
            json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        (a.out / "KIT_SCAN_REPORT.md").write_text(render(report), encoding="utf-8")
        print(f"wrote {a.out / 'kit_scan_results.json'}")
        print(f"wrote {a.out / 'KIT_SCAN_REPORT.md'}")

    print(f"lanes={report['lanes_scanned']} files={report['files_scanned']} "
          f"unscannable={report['files_unscannable']} matches={report['finding_count']}")
    for pattern, count in sorted(report["findings_by_pattern"].items()):
        print(f"  {pattern}: {count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
