# SPDX-License-Identifier: Apache-2.0
"""Generate an entrypoint bound to one complete materialized runtime closure."""
from __future__ import annotations

import json
from typing import Any

from materialize_custody import OPERATION, closure_digest

def _entry_source(expected_inventory: dict[str, dict[str, Any]], arm: str) -> str:
    embedded = json.dumps(expected_inventory, sort_keys=True, separators=(",", ":"))
    expected_closure = closure_digest(expected_inventory)
    return f'''# SPDX-License-Identifier: Apache-2.0\n"""Generated closure-bound {arm} entrypoint for {OPERATION}."""\nfrom __future__ import annotations\nimport hashlib\nimport importlib.util\nimport json\nfrom pathlib import Path\nimport stat\nimport sys\n\nEXPECTED_INVENTORY = json.loads({embedded!r})\nEXPECTED_CLOSURE_SHA256 = {expected_closure!r}\nRUNTIME = Path(__file__).resolve().parent / "runtime"\n\ndef _inventory(root):\n    output = {{}}\n    def visit(directory):\n        for entry in sorted(directory.iterdir(), key=lambda item: item.name):\n            mode = entry.lstat().st_mode\n            if stat.S_ISDIR(mode):\n                visit(entry)\n            elif stat.S_ISREG(mode):\n                data = entry.read_bytes()\n                output[entry.relative_to(root).as_posix()] = {{\n                    "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()\n                }}\n            else:\n                raise RuntimeError(f"non-regular runtime member: {{entry}}")\n    if root.is_symlink() or not root.is_dir():\n        raise RuntimeError("runtime root is missing, non-directory, or symlinked")\n    visit(root)\n    return output\n\ndef _closure(value):\n    payload = json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()\n    return hashlib.sha256(payload).hexdigest()\n\nobserved = _inventory(RUNTIME)\nif observed != EXPECTED_INVENTORY:\n    raise RuntimeError("materialized runtime inventory does not match generated entrypoint")\nif _closure(observed) != EXPECTED_CLOSURE_SHA256:\n    raise RuntimeError("materialized runtime closure digest mismatch")\nfor forbidden in ("candidate", "scheduler", "mechanics"):\n    if forbidden in sys.modules:\n        raise RuntimeError(f"runtime dependency already loaded: {{forbidden}}")\nsys.path.insert(0, str(RUNTIME))\nspec = importlib.util.spec_from_file_location("candidate", RUNTIME / "candidate.py")\nif spec is None or spec.loader is None:\n    raise RuntimeError("cannot create candidate import specification")\nmodule = importlib.util.module_from_spec(spec)\nsys.modules["candidate"] = module\nspec.loader.exec_module(module)\nloaded_scheduler = Path(sys.modules["scheduler"].__file__).resolve()\nif loaded_scheduler != (RUNTIME / "scheduler.py").resolve():\n    raise RuntimeError("scheduler resolved outside the bound runtime")\nagent = module.agent\nif not callable(agent):\n    raise RuntimeError("candidate.agent is not callable")\n'''
