#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
'''Build a diagnostic-only wrapper around an exact certified S13 candidate.'''
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import tempfile

SCHEMA = "titan-v3-s13-activation-capture-receipt/v1"
DIAGNOSTIC_SCHEMA = "titan-v3-s13-certified-activation/v1"
MARKER_NAME = ".titan-v3-s13-capture-activation-v1"
DIAGNOSTIC_NAME = "TITAN-V3-S13-CERTIFIED-ACTIVATION.json"


class ActivationCaptureError(RuntimeError):
    pass


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _atomic_create(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() or path.is_symlink():
        raise ActivationCaptureError(f"refusing to replace existing output: {path}")
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def render_wrapper(candidate_name: str, candidate_sha256: str) -> str:
    if Path(candidate_name).name != candidate_name or not candidate_name.endswith(".py"):
        raise ActivationCaptureError("candidate must be a sibling Python filename")
    return f'''# SPDX-License-Identifier: Apache-2.0
# Generated by activation_capture.py; diagnostics transport only, action bytes unchanged.
from __future__ import annotations
import hashlib, importlib.util, json, os, sys
from pathlib import Path

DIAGNOSTIC_SCHEMA = {DIAGNOSTIC_SCHEMA!r}
MARKER_NAME = {MARKER_NAME!r}
DIAGNOSTIC_NAME = {DIAGNOSTIC_NAME!r}
TARGET_NAME = {candidate_name!r}
TARGET_SHA256 = {candidate_sha256!r}


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {{path}}")
    module = importlib.util.module_from_spec(spec)
    previous = sys.modules.get(name)
    sys.modules[name] = module
    try:
        spec.loader.exec_module(module)
    except BaseException:
        if previous is None:
            sys.modules.pop(name, None)
        else:
            sys.modules[name] = previous
        raise
    return module


_target_path = Path(__file__).resolve().with_name(TARGET_NAME)
if hashlib.sha256(_target_path.read_bytes()).hexdigest() != TARGET_SHA256:
    raise RuntimeError("certified candidate SHA-256 drift")
_candidate = _load("s13_certified_capture_" + TARGET_SHA256[:12], _target_path)


def _publish_diagnostics():
    if not Path(MARKER_NAME).is_file():
        return
    temporary = Path(DIAGNOSTIC_NAME + ".tmp")
    try:
        policy = _candidate.diagnostics()
        payload = {{
            "schema": DIAGNOSTIC_SCHEMA,
            "target_name": TARGET_NAME,
            "target_sha256": TARGET_SHA256,
            "source_seat": getattr(_candidate, "SOURCE_SEAT", None),
            "arm_id": getattr(_candidate, "ARM_ID", None),
            "policy": policy,
        }}
        raw = (json.dumps(payload, sort_keys=True, separators=(",", ":"), allow_nan=False) + "\n").encode()
        temporary.write_bytes(raw)
        os.replace(temporary, DIAGNOSTIC_NAME)
    except (OSError, TypeError, ValueError):
        try:
            temporary.unlink(missing_ok=True)
        except OSError:
            pass


def agent(obs, configuration=None):
    action = _candidate.agent(obs, configuration)
    _publish_diagnostics()
    return action


def diagnostics():
    return _candidate.diagnostics()
'''


def build(candidate: Path, output: Path, receipt: Path, expected_candidate_sha256: str) -> dict:
    if candidate.parent.resolve() != output.parent.resolve():
        raise ActivationCaptureError("candidate and wrapper must be siblings")
    if output.resolve(strict=False) == receipt.resolve(strict=False):
        raise ActivationCaptureError("output and receipt paths alias")
    data = candidate.read_bytes()
    actual = sha256(data)
    if actual != expected_candidate_sha256:
        raise ActivationCaptureError(
            f"candidate SHA-256 mismatch: expected={expected_candidate_sha256} actual={actual}"
        )
    wrapper = render_wrapper(candidate.name, actual).encode()
    result = {
        "schema": SCHEMA,
        "candidate_name": candidate.name,
        "candidate_sha256": actual,
        "wrapper_name": output.name,
        "wrapper_sha256": sha256(wrapper),
        "marker_name": MARKER_NAME,
        "diagnostic_name": DIAGNOSTIC_NAME,
        "diagnostic_schema": DIAGNOSTIC_SCHEMA,
    }
    _atomic_create(output, wrapper)
    _atomic_create(
        receipt,
        (json.dumps(result, indent=2, sort_keys=True, allow_nan=False) + "\n").encode(),
    )
    return result


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--candidate", type=Path, required=True)
    parser.add_argument("--expected-candidate-sha256", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--receipt", type=Path, required=True)
    args = parser.parse_args(argv)
    result = build(
        args.candidate,
        args.output,
        args.receipt,
        args.expected_candidate_sha256,
    )
    print(json.dumps(result, sort_keys=True, allow_nan=False))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ActivationCaptureError, OSError) as exc:
        print(f"ERROR: {exc}", file=os.sys.stderr)
        raise SystemExit(2)
