'use strict';
const $ = id => document.getElementById(id);
const state = { catalog: null };
function iso(id){const v=$(id).value;if(!v)throw new Error('Choose both dates.');const d=new Date(v);if(Number.isNaN(d.valueOf()))throw new Error('Choose valid dates.');return d.toISOString();}
function randomToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}
function requestKey(){return crypto.randomUUID ? crypto.randomUUID() : randomToken();}
function selected(){return state.catalog?.assets.find(x=>x.id===$('asset').value);}
function showQuote(){const a=selected();$('quote').textContent=a?`Rental $${a.rental_subtotal} + booking fee $${a.booking_fee} + refundable deposit $${a.security_deposit} = $${a.amount_due} due before unconfigured taxes/delivery. Availability is not held.`:'';}
async function body(res){const data=await res.json();if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);return data;}
$('check').addEventListener('click',async()=>{try{const start=iso('start'),end=iso('end');const q=new URLSearchParams({start,end});state.catalog=await body(await fetch(`/api/catalog?${q}`));const available=state.catalog.assets.filter(x=>x.available);const select=$('asset');select.replaceChildren();if(available.length){for(const a of available){const option=document.createElement('option');option.value=a.id;option.textContent=`${a.name} — $${a.amount_due}`;select.append(option);}}else{const option=document.createElement('option');option.value='';option.textContent='No assets available';select.append(option);}select.disabled=!available.length;$('submit').disabled=!available.length;showQuote();$('result').textContent=state.catalog.notice;}catch(e){$('result').textContent=e.message;$('submit').disabled=true;}});
$('asset').addEventListener('change',showQuote);
$('request-form').addEventListener('submit',async e=>{e.preventDefault();const token=randomToken();const payload={request_key:requestKey(),status_token:token,asset_id:$('asset').value,start:iso('start'),end:iso('end'),customer:$('customer').value,contact:$('contact').value,notes:$('notes').value};try{const out=await body(await fetch('/api/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}));localStorage.setItem('fleetline-last-request',JSON.stringify({id:out.id,status_token:token}));$('result').textContent=`Request ${out.id} received. ${out.notice}`;$('status-result').textContent=JSON.stringify(out,null,2);}catch(err){$('result').textContent=err.message;}});
$('status').addEventListener('click',async()=>{try{const saved=JSON.parse(localStorage.getItem('fleetline-last-request')||'null');if(!saved)throw new Error('No request is stored in this browser.');const out=await body(await fetch('/api/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(saved)}));$('status-result').textContent=JSON.stringify(out,null,2);}catch(e){$('status-result').textContent=e.message;}});
