"""Compiled motif table. Generated by compile_motifs.py -- do not hand-edit.

A Python literal so the hosted agent reads no disk and runs no model at turn time.
"""

TABLE = {
 "motifs": [
  {
   "op": [
    "BUILD_PASTURE"
   ],
   "when": {
    "tile": "EMPTY"
   },
   "effect": "tile_state_change",
   "role": "worker",
   "observed_roles": [
    "farmer",
    "hand"
   ],
   "proposable": False,
   "hold_reason": "precondition is an empty tile, so the payoff is not local: it depends on a later fill this template cannot see",
   "support": {
    "model": 24,
    "teacher": 0,
    "total": 24
   },
   "provenance": [
    "model"
   ],
   "sources": [
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 4,
     "unit": 0
    },
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 5,
     "unit": 1
    },
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 5,
     "unit": 2
    },
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 8,
     "unit": 1
    },
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 8,
     "unit": 2
    },
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 10,
     "unit": 1
    },
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 10,
     "unit": 2
    },
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 10,
     "unit": 3
    }
   ],
   "id": "m000"
  },
  {
   "op": [
    "PLACE",
    "SHEEP",
    1
   ],
   "when": {
    "tile": "PASTURE",
    "structure==arg_structure": True,
    "arg": "SHEEP",
    "carry[arg]>=n": True
   },
   "effect": "installed_animal",
   "role": "worker",
   "observed_roles": [
    "hand"
   ],
   "proposable": True,
   "hold_reason": None,
   "support": {
    "model": 5,
    "teacher": 0,
    "total": 5
   },
   "provenance": [
    "model"
   ],
   "sources": [
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 19,
     "unit": 1
    },
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 19,
     "unit": 2
    },
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 19,
     "unit": 3
    },
    {
     "trace": "play-sb-on-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 12,
     "unit": 1
    },
    {
     "trace": "play-sb-on-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 12,
     "unit": 2
    }
   ],
   "id": "m003"
  },
  {
   "op": [
    "CARE"
   ],
   "when": {
    "tile": "ANIMAL",
    "cared_today": False,
    "fed_today": False
   },
   "effect": "tile_state_change",
   "role": "worker",
   "observed_roles": [
    "hand"
   ],
   "proposable": True,
   "hold_reason": None,
   "support": {
    "model": 1,
    "teacher": 0,
    "total": 1
   },
   "provenance": [
    "model"
   ],
   "sources": [
    {
     "trace": "play-sb-on-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 18,
     "unit": 1
    }
   ],
   "id": "m001"
  },
  {
   "op": [
    "PICKUP",
    "COW",
    1
   ],
   "when": {
    "shed_access": True,
    "shed[arg]>=n": True,
    "arg": "COW"
   },
   "effect": "tile_state_change",
   "role": "worker",
   "observed_roles": [
    "farmer"
   ],
   "proposable": True,
   "hold_reason": None,
   "support": {
    "model": 1,
    "teacher": 0,
    "total": 1
   },
   "provenance": [
    "model"
   ],
   "sources": [
    {
     "trace": "play-sb-off-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 18,
     "unit": 0
    }
   ],
   "id": "m002"
  },
  {
   "op": [
    "PLANT",
    "MELON"
   ],
   "when": {
    "tile": "EMPTY",
    "seeds[arg]>=1": True,
    "arg": "MELON"
   },
   "effect": "tile_state_change",
   "role": "worker",
   "observed_roles": [
    "hand"
   ],
   "proposable": False,
   "hold_reason": "precondition is an empty tile, so the payoff is not local: it depends on a later fill this template cannot see",
   "support": {
    "model": 1,
    "teacher": 0,
    "total": 1
   },
   "provenance": [
    "model"
   ],
   "sources": [
    {
     "trace": "play-sb-on-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 18,
     "unit": 2
    }
   ],
   "id": "m004"
  },
  {
   "op": [
    "WATER"
   ],
   "when": {
    "tile": "PLANT",
    "watered_today": False,
    "unwatered_run": 1
   },
   "effect": "tile_state_change",
   "role": "worker",
   "observed_roles": [
    "hand"
   ],
   "proposable": True,
   "hold_reason": None,
   "support": {
    "model": 1,
    "teacher": 0,
    "total": 1
   },
   "provenance": [
    "model"
   ],
   "sources": [
    {
     "trace": "play-sb-on-s3131017.json",
     "seed": 3131017,
     "provenance": "model",
     "step": 19,
     "unit": 2
    }
   ],
   "id": "m005"
  }
 ],
 "meta": {
  "compiled_at": "2026-09-07T10:16:27Z",
  "engine_pin": "28b6d8af3ce73926b3d0fda1410c1ddd8384ab8c",
  "traces": [
   "play-sb-off-s3131017.json",
   "play-sb-on-s3131017.json",
   "play-refresh-s3131017.json",
   "play-s5252003-t24.json"
  ],
  "verified_turns": 48,
  "uncompiled_turns": 48,
  "effect_classifier_disagreements": 0,
  "min_support": 1,
  "proposable": 4,
  "held": 2,
  "provenance": "model"
 }
}
