# SPDX-License-Identifier: Apache-2.0
"""Build an isolated executable overlay around the byte-bound scheduler port."""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SPEC = importlib.util.spec_from_file_location(
    "titan_v3_intent_priority_materialize", HERE / "materialize.py"
)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError("cannot load intent-priority materializer")
materialize_module = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(materialize_module)


class OverlayError(RuntimeError):
    pass


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build(source_lab: Path, output: Path, receipt_path: Path) -> dict:
    source_lab = source_lab.resolve(strict=True)
    output = output.resolve()
    receipt_path = receipt_path.resolve()
    source_scheduler = source_lab / "scheduler.py"
    source_main = source_lab / "main.py"
    if not source_scheduler.is_file() or not source_main.is_file():
        raise OverlayError("source lab must contain main.py and scheduler.py")
    try:
        output.relative_to(source_lab)
    except ValueError:
        pass
    else:
        raise OverlayError("overlay must be outside canonical source lab")
    if output.exists() and any(output.iterdir()):
        raise OverlayError("overlay output must be absent or empty")
    output.mkdir(parents=True, exist_ok=True)

    source_before = {
        "main.py": _sha256(source_main),
        "scheduler.py": _sha256(source_scheduler),
    }
    port = materialize_module.materialize(
        source_scheduler,
        output / "scheduler.py",
    )
    candidate_scheduler_sha = port["candidate"]["sha256"]
    entrypoint = f'''# Generated by {materialize_module.OPERATION}; do not edit.\nfrom __future__ import annotations\nimport hashlib\nimport importlib.util\nfrom pathlib import Path\nimport sys\n\nOVERLAY = Path(__file__).resolve().parent\nSOURCE_LAB = Path({str(source_lab)!r})\nEXPECTED_SOURCE_BLOB = {materialize_module.EXPECTED_SCHEDULER_BLOB!r}\nEXPECTED_CANDIDATE_SHA256 = {candidate_scheduler_sha!r}\n\ndef _git_blob(data: bytes) -> str:\n    return hashlib.sha1(f"blob {{len(data)}}\\0".encode("ascii") + data).hexdigest()\n\nsource_bytes = (SOURCE_LAB / "scheduler.py").read_bytes()\ncandidate_bytes = (OVERLAY / "scheduler.py").read_bytes()\nif _git_blob(source_bytes) != EXPECTED_SOURCE_BLOB:\n    raise RuntimeError("intent-priority source scheduler drift")\nif hashlib.sha256(candidate_bytes).hexdigest() != EXPECTED_CANDIDATE_SHA256:\n    raise RuntimeError("intent-priority candidate scheduler drift")\nif "scheduler" in sys.modules:\n    raise RuntimeError("scheduler imported before overlay custody established")\nsys.path.insert(0, str(OVERLAY))\nsys.path.insert(1, str(SOURCE_LAB))\nspec = importlib.util.spec_from_file_location("_titan_v3_intent_priority_main", SOURCE_LAB / "main.py")\nif spec is None or spec.loader is None:\n    raise RuntimeError("cannot load canonical main through overlay")\nmodule = importlib.util.module_from_spec(spec)\nsys.modules[spec.name] = module\nspec.loader.exec_module(module)\nagent = module.agent\n'''
    entrypoint_path = output / "entrypoint.py"
    materialize_module.atomic_write(entrypoint_path, entrypoint.encode("utf-8"))
    compile(entrypoint, str(entrypoint_path), "exec")

    source_after = {
        "main.py": _sha256(source_main),
        "scheduler.py": _sha256(source_scheduler),
    }
    if source_before != source_after:
        raise OverlayError("canonical source changed while building overlay")
    receipt = dict(port)
    receipt["source_files_unchanged"] = source_before
    receipt["execution_surface"] = {
        "entrypoint": "entrypoint.py::agent",
        "entrypoint_sha256": _sha256(entrypoint_path),
        "scheduler_sha256": _sha256(output / "scheduler.py"),
        "source_lab": str(source_lab),
        "isolated_files": ["entrypoint.py", "scheduler.py"],
        "canonical_import": str(source_main),
    }
    materialize_module.atomic_write(
        receipt_path,
        (json.dumps(receipt, indent=2, sort_keys=True) + "\n").encode("utf-8"),
    )
    return receipt


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-lab", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--receipt", type=Path, required=True)
    args = parser.parse_args()
    receipt = build(args.source_lab, args.output, args.receipt)
    print(json.dumps(receipt["execution_surface"], sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
