"""Generated by league/run_league.py — do not edit by hand.

Provenance:
  contestant: v3-kestrel-capital-execution
  entry: cloud-execution-lab/candidates/v3-kestrel-capital-execution/candidate_main.py  sha256=4c7196752137e938296f7b0f631791b74fcb2e91be07a215aefeb638b0f76458
  callable: agent
  support: [{"module": "cloud-runtime-pulse/observed_clone.py", "sha256": "ab92d3c18c8edb63cbdd31626ada447783b85bbe9ed32bb546e6c7834a99b152"}, {"module": "cloud-quickstep/seller_snapshot.py", "sha256": "e7093c760c05400948ece0a4a00495ab2cb93fd56e585eba9eb78b1f13666576"}]
  generated: 2026-09-10T19:13:42.439214+00:00
"""
import sys
sys.path.insert(0, '/tmp/league_panel1/staging/v3-kestrel-capital-execution/support')
sys.path.insert(0, '/home/hatch/workspace/build/wt-adversarial-league/revenue/kaggriculture/cloud-execution-lab')
sys.path.insert(0, '/home/hatch/workspace/build/wt-adversarial-league/revenue/kaggriculture/cloud-execution-lab/candidates/v3-kestrel-capital-execution')
import importlib.util as _ilu
_spec = _ilu.spec_from_file_location('_league_entry_v3_kestrel_capital_execution', '/home/hatch/workspace/build/wt-adversarial-league/revenue/kaggriculture/cloud-execution-lab/candidates/v3-kestrel-capital-execution/candidate_main.py')
_module = _ilu.module_from_spec(_spec)
sys.modules['_league_entry_v3_kestrel_capital_execution'] = _module
_spec.loader.exec_module(_module)
agent = getattr(_module, 'agent')
