"""Embedded Chromium DOM checks; a declared memory adapter is not localStorage proof."""
from pathlib import Path
import json
import re
from playwright.sync_api import sync_playwright

ROOT=Path(__file__).resolve().parent
HTML=re.sub(r'<script src="(?:model|app)\.js"></script>', '', (ROOT/'index.html').read_text())

def load(page, seed=None):
    page.set_content(HTML)
    page.evaluate('''seed => {window.parcelMap=new Map(Object.entries(seed||{}));window.ParcelStorage={getItem:k=>parcelMap.has(k)?parcelMap.get(k):null,setItem:(k,v)=>parcelMap.set(k,v)};}''',seed)
    page.add_script_tag(content=(ROOT/'model.js').read_text())
    page.add_script_tag(content=(ROOT/'app.js').read_text())

def main():
    checks=[]
    def check(name,condition):
        assert condition,name
        checks.append(name)
    with sync_playwright() as p:
        browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
        page=browser.new_page(viewport={'width':1440,'height':1100},accept_downloads=True)
        page.on('dialog',lambda d:d.accept())
        errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
        load(page)
        check('three catalog choices',page.locator('.template').count()==3)
        page.get_by_role('button',name='Open a synthetic example').click()
        check('example opens unrecorded', 'installation not recorded' in page.locator('#progress').inner_text())
        page.locator('[name=agency]').fill('Atlas Agency (synthetic)')
        page.locator('[name=quantity]').fill('2')
        page.locator('[name=includeSupport]').check()
        page.locator('#map-name').fill('full_name')
        page.get_by_role('button',name='Save brief',exact=True).click()
        check('exact invoice preview',page.locator('#first-total').inner_text()=='$2,398.00')
        check('mapping persisted in adapter',page.evaluate("JSON.parse(parcelMap.get('parcel.workspace.v1')).orders[0].mapping.name")=='full_name')
        page.locator('#tab-install').click()
        page.get_by_role('textbox',name='Runner installed in the intended environment note').fill('Synthetic check: existing cloud environment')
        page.locator('#check-installed').check()
        check('installation checkbox saved','1/5 current checks' in page.locator('#progress').inner_text())
        page.locator('#tab-brief').click()
        page.locator('[name=scope]').fill('Changed synthetic scope')
        page.get_by_role('button',name='Save brief',exact=True).click()
        page.locator('#tab-install').click()
        check('scope revision stales installation','installation not recorded' in page.locator('#progress').inner_text())
        check('earlier note preserved','Synthetic check' in page.get_by_role('textbox',name='Runner installed in the intended environment note').input_value())
        check('stale explanation displayed','Earlier specification' in page.locator('#checklist').inner_text())
        page.locator('#tab-delivery').click()
        with page.expect_download() as dl:page.locator('#download-deployment').click()
        payload=json.loads(Path(dl.value.path()).read_text())
        check('actual deployment download',payload['format']=='parcel.intake-handoff' and payload['fieldMapping']['name']=='full_name' and len(payload['tasks'])==3)
        check('export did not install service',payload['recordedInstallation'] is False)
        page.locator('#duplicate').click()
        check('duplicate opens new ID and resets checks',page.locator('#order-count').inner_text()=='2' and page.locator('#progress').inner_text().startswith('0/5'))
        page.locator('#tab-brief').click()
        page.locator('[name=agency]').fill('<img src=x onerror="window.injected=1">')
        page.get_by_role('button',name='Save brief',exact=True).click()
        check('user markup remains text',page.evaluate('window.injected===undefined') and page.locator('#order-label img').count()==0)
        with page.expect_download() as dl:page.locator('#backup').click()
        backup_path=Path(dl.value.path())
        backup=json.loads(backup_path.read_text())
        check('workspace backup contains both orders',len(backup['orders'])==2)
        page.locator('#restore-file').set_input_files({'name':'workspace.json','mimeType':'application/json','buffer':backup_path.read_bytes()})
        page.wait_for_function("document.getElementById('notice').textContent.startsWith('Import complete')")
        check('actual file import restores workspace',page.locator('#order-count').inner_text()=='2')
        page.locator('#search').fill('not-present')
        check('search filters queue','No matching briefs' in page.locator('#orders').inner_text())
        page.locator('#search').fill('')
        page.locator('#tab-brief').click()
        page.locator('[name=agency]').fill('Atlas Agency (synthetic)')
        page.get_by_role('button',name='Save brief',exact=True).click()
        page.screenshot(path=str(ROOT/'desktop-check.png'),full_page=True)
        page.set_viewport_size({'width':390,'height':844})
        check('390px layout has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=window.innerWidth'))
        page.screenshot(path=str(ROOT/'mobile-check.png'),full_page=True)
        page.locator('[name=title]').fill('Unsaved draft')
        page.evaluate("(()=>{const s=JSON.parse(parcelMap.get('parcel.workspace.v1'));s.revision++;parcelMap.set('parcel.workspace.v1',JSON.stringify(s));})()")
        page.get_by_role('button',name='Save brief',exact=True).click()
        check('sequential tab conflict preserves draft','Another tab' in page.locator('#notice').inner_text() and page.locator('[name=title]').input_value()=='Unsaved draft')
        check('stale save did not overwrite adapter',page.evaluate("JSON.parse(parcelMap.get('parcel.workspace.v1')).orders[0].title")!='Unsaved draft')
        with page.expect_download() as dl:page.locator('#backup').click()
        draft=json.loads(Path(dl.value.path()).read_text())
        check('unsaved draft remains exportable',draft['orders'][0]['title']=='Unsaved draft')
        check('no unhandled browser exceptions',not errors)

        fallback=browser.new_page(viewport={'width':900,'height':700})
        fallback_errors=[];fallback.on('pageerror',lambda e:fallback_errors.append(str(e)))
        fallback.set_content(HTML)
        fallback.evaluate('''() => {let reads=0;window.ParcelStorage={getItem:()=>{reads++;if(reads===1)return null;throw new Error('forced read failure');},setItem:()=>{throw new Error('blind storage write after read failure');}};}''')
        fallback.add_script_tag(content=(ROOT/'model.js').read_text())
        fallback.add_script_tag(content=(ROOT/'app.js').read_text())
        fallback.get_by_role('button',name='Open a synthetic example').click()
        check('storage read failure keeps new brief in memory',fallback.locator('#order-count').inner_text()=='1')
        check('storage read failure degrades to memory only','Memory only' in fallback.locator('#storage-status').inner_text())
        check('storage read failure has no unhandled exception',not fallback_errors)
        fallback.close()
        browser.close()
    print(json.dumps({'mode':'embedded DOM with explicit in-memory storage adapter; native navigation blocked','checks':len(checks),'passed':checks},indent=2))

if __name__=='__main__':main()
