'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const M=require('./model.js');
const now='2026-09-08T11:00:00.000Z';
const fresh=(fields={})=>M.newOrder(fields,now,'order-example');
const workspace=(fields={})=>M.addOrder(M.empty(now),fresh(fields),now);
test('three catalog presets have distinct task workflows',()=>{assert.equal(M.CATALOG.length,3);assert.equal(new Set(M.CATALOG.map(c=>JSON.stringify(c.tasks))).size,3);});
test('new workspace is empty and versioned',()=>assert.deepEqual(M.empty(now),{version:1,revision:0,updatedAt:now,orders:[]}));
test('money parsing is exact in cents',()=>{assert.equal(M.dollars('900.10'),90010);assert.equal(M.dollars('0.29'),29);assert.equal(M.dollars('01.1'),110);});
test('money rejects rounding, exponents and negative values',()=>{for(const x of ['1.001','1e3','-1','NaN','Infinity','','1,000',10])assert.throws(()=>M.dollars(x));});
test('setup and optional monthly pricing use integer cents',()=>{let o=fresh({quantity:3,includeSupport:true,setupCents:29,monthlyCents:11});assert.deepEqual(M.quote(o),{setup:87,monthly:33,firstMonth:120,currency:'USD',taxIncluded:false,paymentRecorded:false});});
test('support is not billed when unchecked',()=>assert.equal(M.quote(fresh()).monthly,0));
test('fractional and excessive installation count rejected',()=>{for(const x of [0,1.5,101,NaN])assert.throws(()=>fresh({quantity:x}));});
test('construction resets system fields on duplication',()=>{const o=fresh();const copy=M.newOrder({...o,revision:40,specRevision:30},now,'order-copy');assert.equal(copy.id,'order-copy');assert.equal(copy.revision,1);assert.equal(copy.specRevision,1);});
test('add does not mutate input',()=>{const s=M.empty(now);const next=M.addOrder(s,fresh(),now);assert.equal(s.orders.length,0);assert.equal(next.orders.length,1);});
test('duplicate order ID cannot silently replace a brief',()=>assert.throws(()=>M.addOrder(workspace(),fresh()),/already exists/));
test('update increments revisions without mutating prior state',()=>{const s=workspace(),n=M.updateOrder(s,'order-example',{client:'Another client'},1,now);assert.equal(n.orders[0].revision,2);assert.equal(n.orders[0].specRevision,2);assert.equal(s.orders[0].client,'New client');});
test('stale order write rejected',()=>{let s=M.updateOrder(workspace(),'order-example',{notes:'one'},1,now);assert.throws(()=>M.updateOrder(s,'order-example',{notes:'two'},1,now),/changed/);assert.equal(s.orders[0].notes,'one');});
test('recorded installation starts false',()=>assert.equal(M.progress(fresh()).installed,false));
test('installation records include current revision and note',()=>{const s=M.checkItem(workspace(),'order-example','installed',true,'Existing private cloud',1,now);assert.equal(M.progress(s.orders[0]).installed,true);assert.equal(s.orders[0].checklist.installed.note,'Existing private cloud');});
test('scope change invalidates check without losing note',()=>{let s=M.checkItem(workspace(),'order-example','installed',true,'Actual prior location',1,now);s=M.updateOrder(s,'order-example',{scope:'Different workflow'},2,now);assert.equal(M.progress(s.orders[0]).installed,false);assert.equal(s.orders[0].checklist.installed.done,true);assert.equal(s.orders[0].checklist.installed.note,'Actual prior location');assert.match(M.handoff(s.orders[0]),/earlier specification/);});
test('pricing-only update retains installation record',()=>{let s=M.checkItem(workspace(),'order-example','installed',true,'Cloud',1,now);s=M.updateOrder(s,'order-example',{setupCents:85000},2,now);assert.equal(M.progress(s.orders[0]).installed,true);});
test('mapping change invalidates installation',()=>{let s=M.checkItem(workspace(),'order-example','installed',true,'Cloud',1,now);s=M.updateOrder(s,'order-example',{mapping:{...M.DEFAULT_MAPPING,name:'full_name'}},2,now);assert.equal(M.progress(s.orders[0]).installed,false);});
test('rechecking current specification makes record current',()=>{let s=M.checkItem(workspace(),'order-example','installed',true,'Old',1,now);s=M.updateOrder(s,'order-example',{title:'Changed'},2,now);s=M.checkItem(s,'order-example','installed',true,'New',3,now);assert.equal(M.progress(s.orders[0]).installed,true);});
test('notes do not invalidate installation',()=>{let s=M.checkItem(workspace(),'order-example','installed',true,'Cloud',1,now);s=M.updateOrder(s,'order-example',{notes:'Follow-up'},2,now);assert.equal(M.progress(s.orders[0]).installed,true);});
test('stale checklist write rejected',()=>assert.throws(()=>M.checkItem(workspace(),'order-example','retry',true,'',0,now),/changed/));
test('reopening a checklist item clears current completion',()=>{let s=M.checkItem(workspace(),'order-example','retry',true,'passed',1,now);s=M.checkItem(s,'order-example','retry',false,'retry again',2,now);assert.equal(M.progress(s.orders[0]).done,0);});
test('workspace backup roundtrips losslessly',()=>{const s=workspace();assert.deepEqual(M.validateState(JSON.parse(JSON.stringify(s))),s);});
test('unknown backup format rejected',()=>assert.throws(()=>M.validateState({...workspace(),version:2}),/version/));
test('duplicate IDs in backup rejected',()=>{const s=workspace();s.orders.push(fresh());assert.throws(()=>M.validateState(s),/duplicate/);});
test('bad mapping and prototype names rejected',()=>{assert.throws(()=>fresh({mapping:{...M.DEFAULT_MAPPING,email:'name'}}),/one destination/);assert.throws(()=>fresh({mapping:{...M.DEFAULT_MAPPING,email:'__proto__'}}));});
test('price NaN and string types rejected',()=>{assert.throws(()=>fresh({setupCents:NaN}));assert.throws(()=>fresh({setupCents:'100'}));});
test('CSV quotes and neutralizes formula-like values',()=>{const csv=M.exportCSV(workspace({agency:'=SUM(A1)',client:'Comma, "quote"'}));assert.match(csv,/"'=SUM\(A1\)"/);assert.match(csv,/"Comma, ""quote"""/);});
test('handoff escapes markup from client input',()=>{const output=M.handoff(fresh({agency:'<script>bad</script>'}));assert.ok(!output.includes('<script>'));assert.match(output,/proposal, not a payment receipt/);});
test('stable synthetic example uses all mapped keys',()=>{const o=fresh({mapping:{...M.DEFAULT_MAPPING,name:'full_name'}}),d=M.deployment(o);assert.equal(d.exampleIntake.payload.full_name,'Example Client');assert.equal(d.exampleIntake.payload.name,undefined);assert.equal(d.exampleIntake.id,M.deployment(o).exampleIntake.id);assert.equal(d.recordedInstallation,false);assert.equal(d.tasks.length,3);assert.equal(Object.keys(d.fieldMapping).length,7);});
test('new specification generates a distinct retry-safe smoke ID',()=>{const old=fresh();const n=M.updateOrder(workspace(),'order-example',{scope:'New scope'},1,now).orders[0];assert.notEqual(M.deployment(old).exampleIntake.id,M.deployment(n).exampleIntake.id);});
test('remove is revision-aware and immutable',()=>{const s=workspace();assert.throws(()=>M.removeOrder(s,'order-example',0,now));assert.equal(M.removeOrder(s,'order-example',1,now).orders.length,0);assert.equal(s.orders.length,1);});
test('history stays bounded without truncating current notes',()=>{let s=workspace();for(let i=0;i<210;i++)s=M.updateOrder(s,'order-example',{notes:'revision '+i},s.orders[0].revision,now);assert.equal(s.orders[0].history.length,200);assert.equal(s.orders[0].notes,'revision 209');});

test('largest permitted combined quote can be formatted',()=>{const o=fresh({quantity:100,includeSupport:true,setupCents:999999999,monthlyCents:999999999});assert.equal(M.quote(o).firstMonth,199999999800);assert.equal(M.money(M.quote(o).firstMonth),'$1,999,999,998.00');});
