"""Bounded Slack history/reply reads through the collector's existing budget.

Rows are ephemeral provider observations. Only selected metadata is persisted by
collectors.py; errors never carry raw exception text or arbitrary provider data.
"""
from __future__ import annotations

import re


class SlackReadFailure(RuntimeError):
    def __init__(self, code):
        self.code = code
        super().__init__(code)


def _stamp(value):
    return (isinstance(value, str)
            and re.fullmatch(r"[0-9]{1,12}(?:\.[0-9]{1,6})?", value) is not None
            and int(value.split(".")[0]) <= 253402300799)


def _order(value):
    seconds, _, fraction = value.partition(".")
    return int(seconds), int(fraction.ljust(6, "0") or "0")


def _page(response, limit, root=None):
    if not isinstance(response, dict) or response.get("ok") is not True:
        code = response.get("error") if isinstance(response, dict) else None
        known = {"thread_not_found", "channel_not_found", "missing_scope", "not_in_channel"}
        raise SlackReadFailure(code if isinstance(code, str) and code in known else "slack_response_shape")
    rows = response.get("messages")
    if not isinstance(rows, list) or len(rows) > limit:
        raise SlackReadFailure("slack_messages_shape")
    for row in rows:
        if not isinstance(row, dict) or not _stamp(row.get("ts")):
            raise SlackReadFailure("slack_messages_shape")
        for field in ("thread_ts", "latest_reply"):
            if row.get(field) is not None and not _stamp(row[field]):
                raise SlackReadFailure("slack_messages_shape")
        if ("reply_count" in row and (type(row["reply_count"]) is not int
                or not 0 <= row["reply_count"] <= 2147483647)):
            raise SlackReadFailure("slack_messages_shape")
        if "edited" in row and (not isinstance(row["edited"], dict)
                or not _stamp(row["edited"].get("ts"))):
            raise SlackReadFailure("slack_messages_shape")
        for field in ("subtype", "user", "bot_id"):
            if row.get(field) is not None and not isinstance(row[field], str):
                raise SlackReadFailure("slack_messages_shape")
        if "text" in row and not isinstance(row["text"], str):
            raise SlackReadFailure("slack_messages_shape")
        if root is not None and ((row["ts"] != root and row.get("thread_ts") != root)
                or (row["ts"] == root and row.get("thread_ts", root) != root)):
            raise SlackReadFailure("slack_thread_identity")
    metadata = response.get("response_metadata", {})
    if (not isinstance(metadata, dict)
            or not isinstance(metadata.get("next_cursor", ""), str)
            or len(metadata.get("next_cursor", "")) > 4000
            or type(response.get("has_more", False)) is not bool
            or type(response.get("is_limited", False)) is not bool):
        raise SlackReadFailure("slack_pagination_shape")
    return rows, metadata.get("next_cursor", ""), response.get("has_more", False), response.get("is_limited", False)


def _error(exc):
    known = {"slack_rate_limited", "collector_read_deferred", "refresh_cancelled",
             "refresh_deadline_reached", "thread_not_found", "channel_not_found",
             "missing_scope", "not_in_channel", "slack_response_shape",
             "slack_messages_shape", "slack_pagination_shape", "slack_thread_identity"}
    code = getattr(exc, "code", None)
    result = {"code": code if isinstance(code, str) and code in known else "slack_read_failed"}
    retry = getattr(exc, "retry_not_before", None)
    if retry is None and code == "slack_rate_limited":
        metadata = getattr(exc, "metadata", {})
        retry = metadata.get("retry_not_before") if isinstance(metadata, dict) else None
    # Retry times are generated by RequestBudget, never copied from provider text.
    if isinstance(retry, str) and re.fullmatch(r"[0-9T:.+Z-]{1,40}", retry):
        result["retry_not_before"] = retry
    return result


def _read_pages(read, method, payload, max_pages, *, root=None, propagate_first=False):
    rows, seen, cursor, limited, changed = {}, set(), "", False, False
    report = {"pages_read": 0, "complete": False, "next_cursor": "", "error": None}
    for _ in range(max_pages):
        request = {**payload, **({"cursor": cursor} if cursor else {})}
        try:
            page, next_cursor, has_more, page_limited = _page(read(method, request), payload["limit"], root)
        except Exception as exc:
            if propagate_first and not report["pages_read"]:
                raise
            report.update(error=_error(exc), reason="read_failed", next_cursor=cursor)
            break
        report["pages_read"] += 1
        for row in page:
            old = rows.get(row["ts"])
            if old is not None and any(old.get(key) != row.get(key)
                    for key in ("reply_count", "latest_reply", "thread_ts")):
                changed = True
            rows[row["ts"]] = row
        limited = limited or page_limited
        report["next_cursor"] = next_cursor
        if not next_cursor:
            report.update(complete=not has_more and not limited,
                          reason="history_limited" if limited else "cursor_missing" if has_more else None)
            break
        if next_cursor in seen:
            report["reason"] = "cursor_cycle"
            break
        seen.add(next_cursor)
        cursor = next_cursor
    else:
        report["reason"] = "page_limit"
    if changed:
        report["complete"] = False
        report["reason"] = report.get("reason") or "thread_evidence_changed"
    report["is_limited"] = limited
    return rows, report


def read_channel(read, channel_id, *, page_size, max_pages, max_threads=0, max_thread_pages=2):
    """Return observed rows and honest bounded coverage, without provider writes.

    A first-history failure propagates for the existing source error/deferred
    path. Later failures retain valid pages; per-slice errors belong in metadata
    so WorkstreamStore can ingest those rows without replacing unobserved ones.
    """
    for name, value, low, high in (("page_size", page_size, 1, 100),
            ("max_pages", max_pages, 1, 10), ("max_threads", max_threads, 0, 8),
            ("max_thread_pages", max_thread_pages, 1, 10)):
        if type(value) is not int or not low <= value <= high:
            raise ValueError(name + " is outside its integer bounds.")
    rows, history = _read_pages(read, "conversations.history",
        {"channel": channel_id, "limit": page_size}, max_pages, propagate_first=True)
    candidates = {}
    for row in rows.values():
        root = row.get("thread_ts") or row["ts"]
        if row.get("reply_count", 0) or root != row["ts"]:
            candidates.setdefault(root, {"thread_ts": root, "reply_count": None, "latest_reply": None})
    for root, candidate in candidates.items():
        if root in rows:
            candidate.update(reply_count=rows[root].get("reply_count"), latest_reply=rows[root].get("latest_reply"))
    ordered = sorted(candidates, key=lambda root: (_order(candidates[root]["latest_reply"] or root), _order(root)), reverse=True)
    evidence, finished = [], set()
    for root in ordered[:max_threads]:
        replies, report = _read_pages(read, "conversations.replies",
            {"channel": channel_id, "ts": root, "limit": page_size}, max_thread_pages, root=root)
        parent = replies.get(root, {})
        counts = [count for count in (candidates[root]["reply_count"], parent.get("reply_count")) if count is not None]
        expected = max(counts) if counts else None
        observed = set(replies) - {root}
        anchors = {value for value in (candidates[root]["latest_reply"], parent.get("latest_reply")) if value}
        if report["complete"] and (root not in replies or expected is None
                or len(observed) != expected or not anchors.issubset(observed)):
            report.update(complete=False, reason="reply_evidence_mismatch")
        if report["complete"]:
            finished.add(root)
        # A broadcast and its reply have the same stable message identity.
        rows.update(replies)
        evidence.append({"thread_ts": root, "expected_replies": expected,
                         "observed_replies": len(observed), **report})
    pending = [candidates[root] for root in ordered if root not in finished]
    metadata = {"history_complete": history["complete"], "next_cursor": history["next_cursor"],
        "history": history, "thread_expansion_enabled": max_threads > 0,
        "threads_observed_count": len(candidates), "threads_read_count": len(evidence),
        "threads_complete_count": len(finished), "thread_coverage": evidence,
        "threads_pending": pending[:100], "threads_pending_count": len(pending),
        "threads_pending_truncated": len(pending) > 100}
    return list(rows.values()), metadata, history["complete"] and not pending
