# SPDX-License-Identifier: Apache-2.0
"""Weekly round-robin runner for the TITAN v3 adversarial league.

Plays the canonical v3 candidate plus every registered challenger against
the vendored public-opponent bank, BOTH seats, identical seeds, through
the unmodified reference evaluator (`reference/evaluator/evaluate.py`)
with the pinned official engine (ENGINE_REF pin asserted by the
evaluator itself).  No simplified mechanics: every match is real
candidate entrypoints vs real opponent code on both seats.

Layout per run, under ``bank/v3-adversarial/league/runs/<utc-stamp>/``:

- ``staging/<name>/support/*.py`` — verbatim copies of the contestant's
  declared support modules (observed_clone, seller_snapshot, ...)
- ``staging/<name>/<name>_entry.py`` — generated bootstrap: puts the
  support dir on sys.path, then imports the real candidate entrypoint by
  absolute path.  The candidate source itself is never copied or edited.
- ``shards/shard_*.json`` — raw evaluator reports
- ``games.jsonl`` — one row per completed cell
- ``report.json`` / ``SUMMARY.md`` — aggregates, strata, alarms

The Elo/lean ledger lives at ``bank/v3-adversarial/league/ledger.json``
(shared across weeks); the alarm baseline is the prior week's joint
(opponent, seat) own-cash means for each contestant.

Faithfulness note: each shard is an independent evaluator process over a
disjoint seed subset, exactly the gauntlet_s11 sharding argument — shard
assignment cannot change any game result because per-game state is
rebuilt from (seed, seat, rng_seed, specs) only.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile
import time
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
LAB = HERE.parent
REPO_ROOT = LAB.parent  # revenue/kaggriculture/

sys.path.insert(0, str(HERE))
from alarms import check_own_cash_regressions, alarms_to_markdown  # noqa: E402
from ledger import load_ledger, save_ledger, record_results, standings  # noqa: E402
from registration import load_registry, sha256_file  # noqa: E402

EVALUATOR = LAB / "reference" / "evaluator" / "evaluate.py"
ENGINE_DIR = LAB / "reference" / "engine"
LOADER = REPO_ROOT / "20260907-offline-agent" / "evaluate.py"
BANK = LAB / "bank" / "v3-adversarial"
LEAGUE_DIR = BANK / "league"

BOOTSTRAP_TEMPLATE = '''"""Generated by league/run_league.py — do not edit by hand.

Provenance:
  contestant: {name}
  entry: {entry}  sha256={entry_sha256}
  callable: {callable_name}
  support: {support_provenance}
  generated: {generated}
"""
import sys
sys.path.insert(0, {support_dir!r})
sys.path.insert(0, {lab_dir!r})
sys.path.insert(0, {entry_dir!r})
import importlib.util as _ilu
_spec = _ilu.spec_from_file_location({module_name!r}, {entry_path!r})
_module = _ilu.module_from_spec(_spec)
sys.modules[{module_name!r}] = _module
_spec.loader.exec_module(_module)
agent = getattr(_module, {callable_name!r})
'''


class LeagueError(ValueError):
    pass


def load_config(path: Path) -> dict:
    data = json.loads(Path(path).read_text())
    required = ("canonical", "opponents", "seeds", "workers")
    for key in required:
        if key not in data:
            raise LeagueError(f"config missing {key!r}")
    return data


def shard_list(items: list, n: int) -> list[list]:
    out: list[list] = [[] for _ in range(max(1, n))]
    for i, item in enumerate(items):
        out[i % len(out)].append(item)
    return [x for x in out if x]


def stage_contestant(name: str, entry: str, callable_name: str,
                     support_modules: list[str], staging: Path) -> dict:
    """Stage one contestant. Returns fingerprint info for the run report."""
    entry_path = (REPO_ROOT / entry).resolve()
    if not entry_path.is_file():
        raise LeagueError(f"contestant {name}: entry not found: {entry}")
    contest_dir = Path(staging) / name
    support_dir = contest_dir / "support"
    support_dir.mkdir(parents=True, exist_ok=True)
    support_provenance = []
    for module in support_modules:
        source = (REPO_ROOT / module).resolve()
        if not source.is_file():
            raise LeagueError(f"contestant {name}: support module missing: {module}")
        digest = sha256_file(source)
        (support_dir / source.name).write_bytes(source.read_bytes())
        support_provenance.append({"module": module, "sha256": digest})
    module_name = f"_league_entry_{name}".replace("-", "_")
    bootstrap = BOOTSTRAP_TEMPLATE.format(
        name=name, entry=entry, entry_sha256=sha256_file(entry_path),
        callable_name=callable_name,
        support_provenance=json.dumps(support_provenance),
        generated=datetime.now(timezone.utc).isoformat(),
        support_dir=str(support_dir), lab_dir=str(LAB),
        entry_dir=str(entry_path.parent),
        module_name=module_name, entry_path=str(entry_path),
    )
    bootstrap_path = contest_dir / f"{name}_entry.py"
    bootstrap_path.write_text(bootstrap)
    return {
        "name": name,
        "entry": entry,
        "callable": callable_name,
        "entry_sha256": sha256_file(entry_path),
        "support": support_provenance,
        "bootstrap": str(bootstrap_path),
        "bootstrap_sha256": sha256_file(bootstrap_path),
    }


def run_shard(contestant_fp: dict, opponents: dict[str, str], seeds: list[int],
              outdir: Path, action_timeout: float, game_timeout: float,
              rng_seed: int) -> dict:
    """One evaluator process over a disjoint seed subset for one contestant."""
    outdir.mkdir(parents=True, exist_ok=True)
    out_path = outdir / f"shard_{contestant_fp['name']}_{seeds[0]}.json"
    cmd = [sys.executable, "-B", str(EVALUATOR),
           "--engine-dir", str(ENGINE_DIR),
           "--loader", str(LOADER),
           "--candidate", f"{contestant_fp['bootstrap']}::agent",
           "--seeds", ",".join(str(s) for s in seeds),
           "--rng-seed", str(rng_seed),
           "--action-timeout", str(action_timeout),
           "--game-timeout", str(game_timeout),
           "--output", str(out_path)]
    for label, spec in opponents.items():
        cmd += ["--opponent", f"{label}={spec}"]
    started = time.time()
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=3600)
    games = []
    for line in proc.stdout.splitlines():
        if line.startswith('{"opponent"'):
            games.append(json.loads(line))
    return {"contestant": contestant_fp["name"], "seeds": seeds,
            "seconds": round(time.time() - started, 1),
            "games": games, "returncode": proc.returncode,
            "stderr_tail": proc.stderr[-2000:]}


def own_cash_of(game: dict) -> float | None:
    if game.get("status") != "complete" or not game.get("scores"):
        return None
    seat = game.get("candidate_seat")
    try:
        value = float(game["scores"][seat])
    except (TypeError, IndexError, KeyError):
        return None
    return value if value == value else None  # reject NaN


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", default=str(HERE / "config.json"))
    parser.add_argument("--outdir", default=None,
                        help="run dir; default bank/v3-adversarial/league/runs/<utc-stamp>")
    parser.add_argument("--workers", type=int, default=None)
    parser.add_argument("--seeds", default=None, help="comma-separated seed override")
    parser.add_argument("--opponents", default=None, help="comma-separated opponent override")
    parser.add_argument("--dry-run", action="store_true",
                        help="stage + plan only; play no games")
    parser.add_argument("--resume", action="store_true",
                        help="reuse existing shards/*.json in --outdir; play no games")
    parser.add_argument("--ledger", default=None,
                        help="ledger path; default bank/v3-adversarial/league/ledger.json")
    args = parser.parse_args(argv)

    config = load_config(args.config)
    seeds = [int(s) for s in (args.seeds or ",".join(
        str(s) for s in config["seeds"])).split(",")]
    opponents = {name: f"{BANK}/{name}/agent.py::agent"
                 for name in (args.opponents.split(",") if args.opponents
                              else config["opponents"])}
    workers = args.workers or int(config["workers"])

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    run_dir = Path(args.outdir) if args.outdir else LEAGUE_DIR / "runs" / stamp
    staging = run_dir / "staging"
    shards_dir = run_dir / "shards"

    canon = config["canonical"]
    contestants = [{
        "name": canon["name"],
        "entry": canon["entry"],
        "callable": canon.get("callable", "agent"),
        "support_modules": canon.get("support_modules", []),
    }]
    for challenger in load_registry(HERE / "challengers"):
        contestants.append({
            "name": challenger["name"],
            "entry": challenger["entry"],
            "callable": challenger.get("callable", "agent"),
            "support_modules": challenger.get("support_modules", []),
        })

    fingerprints = [stage_contestant(c["name"], c["entry"], c["callable"],
                                     c["support_modules"], staging)
                    for c in contestants]

    LEAGUE_DIR.mkdir(parents=True, exist_ok=True)
    plan = {"run": stamp, "seeds": seeds,
            "contestants": [f["name"] for f in fingerprints],
            "opponents": sorted(opponents), "workers": workers,
            "cells_per_contestant": len(opponents) * len(seeds) * 2}
    (run_dir / "plan.json").parent.mkdir(parents=True, exist_ok=True)
    (run_dir / "plan.json").write_text(json.dumps(plan, indent=2) + "\n")
    print(json.dumps(plan))
    if args.dry_run:
        print("dry run: staged, no games played")
        return 0

    t0 = time.time()
    if args.resume:
        shard_results = []
        for shard_path in sorted(shards_dir.glob("shard_*.json")):
            report = json.loads(shard_path.read_text())
            stem = shard_path.stem[len("shard_"):]
            contestant = stem.rsplit("_", 1)[0]  # shard_<name>_<first-seed>.json
            shard_results.append({
                "contestant": contestant,
                "seeds": report.get("seeds", []),
                "seconds": 0.0,
                "games": report.get("games", []),
                "returncode": 0,
                "stderr_tail": "",
                "resumed": True,
            })
        if not shard_results:
            raise LeagueError(f"--resume found no shards in {shards_dir}")
        print(f"resumed {len(shard_results)} shards from {shards_dir}")
    else:
        jobs = []
        for fp in fingerprints:
            for seed_group in shard_list(seeds, workers):
                jobs.append((fp, seed_group))
        with ThreadPoolExecutor(max_workers=len(jobs)) as pool:
            futures = [pool.submit(run_shard, fp, opponents, group, shards_dir,
                                   float(config.get("action_timeout", 15.0)),
                                   float(config.get("game_timeout", 1200.0)),
                                   int(config.get("rng_seed", 20260907)))
                       for fp, group in jobs]
            shard_results = [f.result() for f in futures]
    wall = time.time() - t0

    # ---- aggregate ----
    games_rows: list[dict] = []
    cells: dict[str, list[dict]] = {}
    for shard in shard_results:
        for game in shard["games"]:
            row = {"contestant": shard["contestant"],
                   "opponent": game["opponent"], "seed": game["seed"],
                   "candidate_seat": game["candidate_seat"],
                   "status": game["status"],
                   "scores": game.get("scores"),
                   "failure": game.get("failure")}
            own = own_cash_of(game)
            if own is not None:
                row["own_cash"] = own
                row["margin"] = (game["scores"][game["candidate_seat"]]
                                 - game["scores"][1 - game["candidate_seat"]])
            games_rows.append(row)
            if own is not None:
                cells.setdefault(shard["contestant"], []).append(row)
    with (run_dir / "games.jsonl").open("w") as handle:
        for row in games_rows:
            handle.write(json.dumps(row, allow_nan=False) + "\n")

    ledger_path = Path(args.ledger) if args.ledger else LEAGUE_DIR / "ledger.json"
    ledger = load_ledger(ledger_path)
    alarm_sections = []
    all_alarms: dict[str, list] = {}
    for fp in fingerprints:
        name = fp["name"]
        raw_baseline = (ledger.get("own_cash_baseline") or {}).get(name) or {}
        baseline = {}
        for key, value in raw_baseline.items():
            opp, _, seat = key.rpartition("@")
            baseline[(opp, int(seat))] = value
        contest_cells = [{"opponent": r["opponent"],
                          "candidate_seat": r["candidate_seat"],
                          "own_cash": r["own_cash"]}
                         for r in cells.get(name, [])]
        alarms = check_own_cash_regressions(
            contest_cells, baseline,
            floor=float(config.get("alarm_floor", 0.0)),
            drop_tolerance=float(config.get("alarm_drop_tolerance", 10000.0)))
        all_alarms[name] = alarms
        alarm_sections.append(alarms_to_markdown(name, alarms))
        # refresh baseline from this week's strata means
        strata_sums: dict[tuple[str, int], list[float]] = {}
        for row in contest_cells:
            strata_sums.setdefault((row["opponent"], row["candidate_seat"]),
                                   []).append(row["own_cash"])
        ledger.setdefault("own_cash_baseline", {})[name] = {
            f"{opp}@{seat}": sum(v) / len(v) for (opp, seat), v in strata_sums.items()}

    completed = [r for r in games_rows if r.get("margin") is not None]
    record_results(ledger["players"], [
        {"contestant": r["contestant"], "opponent": r["opponent"], "margin": r["margin"]}
        for r in completed])
    ledger["runs"].append({"stamp": stamp, "plan": plan,
                           "wall_seconds": round(wall, 1),
                           "completed": len(completed),
                           "scheduled": len(games_rows),
                           "alarms": {k: len(v) for k, v in all_alarms.items()}})

    report = {
        "schema": "titan.league-run.v1",
        "stamp": stamp,
        "wall_seconds": round(wall, 1),
        "plan": plan,
        "fingerprints": fingerprints,
        "standings": standings(ledger["players"]),
        "alarms": all_alarms,
        "shards": [{"contestant": s["contestant"], "seeds": s["seeds"],
                    "seconds": s["seconds"], "returncode": s["returncode"],
                    "games": len(s["games"])} for s in shard_results],
    }
    (run_dir / "report.json").write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")

    alarms_md = ["# League own-cash alarms", "", f"Run `{stamp}`", ""]
    alarms_md.extend(alarm_sections)
    (run_dir / "ALARMS.md").write_text("\n".join(alarms_md))
    (LEAGUE_DIR / "ALARMS.md").write_text(
        f"# Latest league alarms (`{stamp}`)\n\n" + "\n".join(alarm_sections))

    summary = [f"# League run {stamp}", "",
               f"wall {wall:.1f}s, {len(completed)}/{len(games_rows)} cells complete", "",
               "## Standings (Elo)", ""]
    for row in standings(ledger["players"]):
        summary.append(
            f"- {row['name']}: elo {row['elo']} "
            f"W{row['wins']}/T{row['ties']}/L{row['losses']} "
            f"mean_margin {row['mean_margin']}")
    summary += ["", "## Alarms",
                f"{sum(len(v) for v in all_alarms.values())} total"]
    (run_dir / "SUMMARY.md").write_text("\n".join(summary) + "\n")

    save_ledger(ledger_path, ledger)
    print(f"done: {len(completed)}/{len(games_rows)} complete in {wall:.1f}s; "
          f"alarms={sum(len(v) for v in all_alarms.values())}")
    return 0 if all(s["returncode"] == 0 for s in shard_results) else 2


if __name__ == "__main__":
    raise SystemExit(main())
