#!/usr/bin/env python3
"""muhl_fractal.py -- a GATE-LEVEL MANDELBROT / JULIA renderer on Bryce's Muhlnickel substrate.

The escape-time fractal is the cleanest possible demonstration of EMERGENCE from a fabricated
rule: the ENTIRE Mandelbrot set -- infinite boundary complexity, self-similar to any depth -- is
generated by iterating one two-number rule, z = z^2 + c, over the complex plane. Here that rule is
not floating-point host arithmetic; it is fabricated as a NAND/AND/OR/XOR netlist with the White Box
compiler: a signed fixed-point complex multiply-and-add (z_r^2 - z_i^2 + c_r, 2 z_r z_i + c_i) plus an
escape test |z|^2 > 4, built from muhl_flex.add_bits and a signed shift-add multiplier.

The fabricated z^2+c step is verified BYTE-EXACT against an independent Python fixed-point reference
before it is used to render anything. Then the same fixed circuit is iterated per pixel to paint an
ASCII Mandelbrot. Resident RAM stays FLAT: the picture is not stored, it is computed from a 2-number
rule addressed in place -- infinite complexity out of a tiny fabricated law. That is emergence.

No numpy, no floats in the fabricated datapath, no touching titan.gguf. PYTHONUTF8=1.
"""
import sys, os, time, ctypes, gc
from ctypes import wintypes
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, r"C:/llm/sdc_sandbox")
import sdc_cc as CC
from muhl_flex import add_bits, mux1, muxw, consts, bit, rd, setf

# ---- resident-RAM meter (Windows working set), same instrument the other engines use ----
class PMC(ctypes.Structure):
    _fields_ = [("cb", wintypes.DWORD), ("PageFaultCount", wintypes.DWORD),
                ("PeakWorkingSetSize", ctypes.c_size_t), ("WorkingSetSize", ctypes.c_size_t)] + \
               [("_%d" % i, ctypes.c_size_t) for i in range(6)]
_k32 = ctypes.WinDLL("kernel32.dll"); _k32.GetCurrentProcess.restype = wintypes.HANDLE
_ps = ctypes.WinDLL("psapi.dll")
_ps.GetProcessMemoryInfo.argtypes = [wintypes.HANDLE, ctypes.c_void_p, wintypes.DWORD]
_ps.GetProcessMemoryInfo.restype = wintypes.BOOL
_h = _k32.GetCurrentProcess()
def rss_mb():
    m = PMC(); m.cb = ctypes.sizeof(PMC)
    _ps.GetProcessMemoryInfo(_h, ctypes.byref(m), m.cb)
    return m.WorkingSetSize / (1024 * 1024)

# ============================ fixed-point format ============================
W = 20                 # signed two's-complement word width  (range +/- 128.0)
F = 12                 # fractional bits  (resolution 1/4096 ~= 0.000244)
MASK = (1 << W) - 1
ONE  = 1 << F          # 1.0 in fixed point
THR  = 4 << F          # escape threshold |z|^2 > 4.0

def to_signed(u):
    return u - (1 << W) if (u >> (W - 1)) & 1 else u
def to_fixed(x):
    return int(round(x * ONE)) & MASK

# ============================ gate helpers ============================
def negate_g(g, a):                                   # two's-complement negate, width = len(a)
    s, _ = add_bits(g, [g.NOT(t) for t in a], consts(g, 1, len(a)))
    return s

def umul(g, A, Bb):                                   # unsigned n-bit * m-bit -> (n+m)-bit shift-add array
    n, m = len(A), len(Bb); wid = n + m
    acc = [g.C0] * wid
    for j in range(m):
        term = ([g.C0] * j + [g.AND(A[i], Bb[j]) for i in range(n)] + [g.C0] * wid)[:wid]
        acc, _ = add_bits(g, acc, term)
    return acc

def smul(g, A, Bb):                                   # signed W-bit * W-bit -> 2W-bit two's complement
    sA, sB = A[-1], Bb[-1]
    magA = muxw(g, sA, negate_g(g, A), A)             # |A|
    magB = muxw(g, sB, negate_g(g, Bb), Bb)           # |B|
    P = umul(g, magA, magB)                           # 2W-bit magnitude product
    sign = g.XOR(sA, sB)
    return muxw(g, sign, negate_g(g, P), P)           # apply product sign

def fmul(g, A, Bb):                                   # fixed-point multiply: (A*B) >> F, arithmetic
    P = smul(g, A, Bb)                                # 2W-bit two's complement
    return P[F:F + W]                                 # >> F, keep low W bits (signed)

# ============================ the fabricated z = z^2 + c step ============================
def build_iteration():
    """One Mandelbrot/Julia update fabricated as gates.
       inputs  (LSB-first, W bits each): z_r, z_i, c_r, c_i
       outputs (LSB-first):              new z_r (W), new z_i (W), escaped (1 bit)"""
    NIN = 4 * W
    g = CC.CircuitCompiler(NIN); IN = g.IN
    zr = [IN[0 * W + i] for i in range(W)]
    zi = [IN[1 * W + i] for i in range(W)]
    cr = [IN[2 * W + i] for i in range(W)]
    ci = [IN[3 * W + i] for i in range(W)]

    zr2  = fmul(g, zr, zr)                             # z_r^2
    zi2  = fmul(g, zi, zi)                             # z_i^2
    zrzi = fmul(g, zr, zi)                             # z_r * z_i

    # new z_r = z_r^2 - z_i^2 + c_r
    t1, _ = add_bits(g, zr2, negate_g(g, zi2))
    nzr, _ = add_bits(g, t1, cr)
    # new z_i = 2 z_r z_i + c_i         (2x = shift left 1)
    sh = [g.C0] + zrzi[:W - 1]
    nzi, _ = add_bits(g, sh, ci)
    # magnitude |z|^2 = z_r^2 + z_i^2   (both non-negative, fits in W bits)
    mag, _ = add_bits(g, zr2, zi2)
    # escaped = mag > THR  <=>  mag >= THR+1  <=>  carry-out of (mag + ~(THR+1) + 1)
    thr = consts(g, THR + 1, W)
    _, esc = add_bits(g, mag, [g.NOT(t) for t in thr], g.C1)

    outs = nzr + nzi + [esc]
    gates, out2 = g.dce(outs)
    run = g.compile_ripple(gates, 2 + g.n_in + len(gates))
    nzr_w, nzi_w, esc_w = out2[0:W], out2[W:2 * W], out2[2 * W]
    # critical-path depth
    base = 2 + g.n_in
    dep = [0] * (base + len(gates))
    for i, (op, a, b) in enumerate(gates):
        dep[base + i] = 1 + max(dep[a], dep[b])
    depth = max(dep[w] for w in out2)
    return run, (nzr_w, nzi_w, esc_w), len(gates), depth

# ============================ independent fixed-point reference ============================
def ref_step(zr_u, zi_u, cr_u, ci_u):
    zr, zi = to_signed(zr_u), to_signed(zi_u)
    cr, ci = to_signed(cr_u), to_signed(ci_u)
    fm = lambda a, b: (a * b) >> F                     # arithmetic fixed-point multiply
    zr2 = fm(zr, zr); zi2 = fm(zi, zi); zrzi = fm(zr, zi)
    nzr = (to_signed(zr2 & MASK) - to_signed(zi2 & MASK) + cr) & MASK
    nzi = ((to_signed((zrzi & MASK)) << 1) + ci) & MASK
    mag = ((zr2 & MASK) + (zi2 & MASK)) & MASK
    esc = 1 if mag > THR else 0
    return nzr, nzi, esc

# ============================ verification ============================
def verify(run, wires, cases=4000):
    import random
    nzr_w, nzi_w, esc_w = wires
    rng = random.Random(1234)
    bad = 0
    # a spread of structured points (real orbit values) plus random words
    probes = []
    for _ in range(cases):
        # keep magnitudes in the reachable orbit band so the check exercises real trajectories
        zr = to_fixed(rng.uniform(-6.5, 6.5)); zi = to_fixed(rng.uniform(-6.5, 6.5))
        cr = to_fixed(rng.uniform(-2.5, 1.0)); ci = to_fixed(rng.uniform(-1.3, 1.3))
        probes.append((zr, zi, cr, ci))
    # plus fully-random bit patterns (stress the datapath, not just the orbit)
    for _ in range(cases):
        probes.append((rng.getrandbits(W), rng.getrandbits(W), rng.getrandbits(W), rng.getrandbits(W)))
    inp = [0] * (4 * W)
    for zr, zi, cr, ci in probes:
        setf(inp, 0 * W, W, zr); setf(inp, 1 * W, W, zi)
        setf(inp, 2 * W, W, cr); setf(inp, 3 * W, W, ci)
        v = run(inp, 1)
        got = (rd(v, nzr_w), rd(v, nzi_w), bit(v, esc_w))
        exp = ref_step(zr, zi, cr, ci)
        if got != exp:
            bad += 1
            if bad <= 3:
                print(f"    MISMATCH z=({zr},{zi}) c=({cr},{ci})  gate={got} ref={exp}")
    return len(probes), bad

# ============================ escape iteration (drive the fabricated rule) ============================
def escape_count(run, wires, cr_u, ci_u, maxiter):
    nzr_w, nzi_w, esc_w = wires
    inp = [0] * (4 * W)
    setf(inp, 2 * W, W, cr_u); setf(inp, 3 * W, W, ci_u)   # c is fixed for this pixel
    zr_u = 0; zi_u = 0                                     # z starts at 0
    for it in range(maxiter):
        setf(inp, 0 * W, W, zr_u); setf(inp, 1 * W, W, zi_u)
        v = run(inp, 1)
        if bit(v, esc_w):
            return it                                     # |z| > 2 -> escaped
        zr_u = rd(v, nzr_w); zi_u = rd(v, nzi_w)
    return maxiter                                        # survived -> in the set

def render(run, wires, cols=78, rows=34, maxiter=40,
           rmin=-2.30, rmax=0.75, imin=-1.20, imax=1.20, peakbox=None):
    PAL = " .,-~:;=+*oxX$&#@"                             # fast-escape -> space, in-set -> '@'
    L = len(PAL)
    lines = []
    for ry in range(rows):
        if peakbox is not None:                           # track resident RAM AS the image is painted
            peakbox[0] = max(peakbox[0], rss_mb())
        ci = to_fixed(imin + (imax - imin) * ry / (rows - 1))
        row = []
        for rx in range(cols):
            cr = to_fixed(rmin + (rmax - rmin) * rx / (cols - 1))
            it = escape_count(run, wires, cr, ci, maxiter)
            if it >= maxiter:
                row.append('@')
            else:
                row.append(PAL[min(it * L // maxiter, L - 1)])
        lines.append("".join(row))
    return lines

# ============================ main ============================
def main():
    print("\n  MUHLNICKEL FRACTAL -- z = z^2 + c fabricated as gates; the Mandelbrot set emerges\n", flush=True)
    print(f"  fixed-point format: {W}-bit signed, {F} fractional bits (range +/-{(1<<(W-1))/ONE:.0f}.0, res 1/{ONE})", flush=True)

    t = time.time()
    run, wires, ng, depth = build_iteration()
    print(f"  fabricated z^2+c step: {ng:,} gates, critical-path depth {depth}"
          f"  (3 signed fixed-point multipliers + complex add + |z|^2>4 test)   [{time.time()-t:.1f}s]", flush=True)

    # ---- byte-exact verification vs the independent fixed-point reference ----
    t = time.time()
    n, bad = verify(run, wires)
    status = "BYTE-EXACT" if bad == 0 else f"{bad} MISMATCH"
    print(f"  verify vs Python fixed-point reference: {n:,} cases -> {status}   [{time.time()-t:.1f}s]", flush=True)
    if bad:
        return 1

    # ---- render the ASCII Mandelbrot, measuring resident RAM across the whole picture ----
    print("\n  rendering the Mandelbrot set by iterating the fabricated rule per pixel...\n", flush=True)
    gc.collect()                                          # settle a clean baseline
    rss0 = rss_mb(); peakbox = [rss0]; t = time.time()
    lines = render(run, wires, peakbox=peakbox)
    dt = time.time() - t; rss1 = rss_mb(); peak = peakbox[0]

    print("  +" + "-" * len(lines[0]) + "+")
    for ln in lines:
        print("  |" + ln + "|")
    print("  +" + "-" * len(lines[0]) + "+")

    npx = len(lines) * len(lines[0])
    print(f"\n  {len(lines[0])}x{len(lines)} = {npx:,} pixels, each an orbit of the fabricated 2-number rule.")
    print(f"  render time {dt:.1f}s.  resident RAM: start {rss0:.1f} MB, PEAK {peak:.1f} MB, end {rss1:.1f} MB"
          f"  (peak delta {peak-rss0:+.2f} MB across all {npx:,} pixels)")
    print(f"  The image is NOT stored -- it is computed from z=z^2+c addressed in place, so RAM stays FLAT")
    print(f"  no matter how deep the boundary detail runs. Infinite complexity from a tiny fabricated law.")
    print(f"\n  Julia sets are the SAME circuit: fix c, sweep z0 over the plane instead. One rule, endless form.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
