#!/usr/bin/env python3
"""Report production structure for University of Iowa RFQ 18649 (UIOWA-082).

STATUS: PROPOSED REPORT STRUCTURE / NOT A UNIVERSITY FINDING.

What this is
------------
`content_map.json` maps every required RFQ report element to a report section and
to the inputs that section needs. This module makes that map *executable*: it
loads the map, checks its coverage, verifies the declared inputs against the
field names the other RFQ lanes actually landed, and renders both the editable
template and a populated synthetic sample from the same structure.

Why the checker fails closed on "a section with no source"
----------------------------------------------------------
A final report fails in two directions. An RFQ element with no section is the
obvious one and is easy to catch. The quieter one is a prose section that cites
nothing: that is exactly where an unsupported assertion enters a report and then
gets quoted back as a finding. So a section declaring no required input is an
error, not a style note.

Why the field names are not invented
------------------------------------
`input_schemas.json` was generated by reading the headers of the registers other
seats actually checked in - the EV/OBS/FND evidence chain, the peer
comparability table, the policy context register, the framework crosswalk, the
SDLC worksheet. `--verify-workbench` re-reads those files and fails if a pinned
field name has drifted. A template that renames its neighbours' fields is a
template nobody can feed.

Python 3 standard library only. No network.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from dataclasses import dataclass, field
from typing import Any, Sequence

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_MAP = os.path.join(HERE, "content_map.json")
DEFAULT_SCHEMAS = os.path.join(HERE, "input_schemas.json")
DEFAULT_FIXTURES = os.path.join(HERE, "fixtures")

# Severity for a coverage issue. ERROR fails the check; WARN is reported and
# does not fail, so the checker stays usable on a report still being drafted.
ERROR = "ERROR"
WARN = "WARN"

UNKNOWN_TOKEN = "UNKNOWN"


@dataclass
class Issue:
    code: str
    severity: str
    subject: str
    detail: str

    def __str__(self) -> str:
        return f"[{self.severity}] {self.code}  {self.subject}: {self.detail}"


@dataclass
class ContentMap:
    raw: dict
    elements: list[dict] = field(default_factory=list)
    sections: list[dict] = field(default_factory=list)
    excluded: list[dict] = field(default_factory=list)

    @property
    def element_ids(self) -> list[str]:
        return [e["element_id"] for e in self.elements]

    @property
    def section_ids(self) -> list[str]:
        return [s["section_id"] for s in self.sections]

    def element(self, eid: str) -> dict | None:
        return next((e for e in self.elements if e["element_id"] == eid), None)

    def sections_for(self, eid: str) -> list[dict]:
        return [s for s in self.sections if eid in s.get("covers", [])]


def load_map(path: str = DEFAULT_MAP) -> ContentMap:
    with open(path, encoding="utf-8") as f:
        raw = json.load(f)
    return ContentMap(raw=raw,
                      elements=raw.get("rfq_elements", []),
                      sections=raw.get("sections", []),
                      excluded=raw.get("excluded_deliverables", []))


def load_schemas(path: str = DEFAULT_SCHEMAS) -> dict[str, dict]:
    with open(path, encoding="utf-8") as f:
        return json.load(f).get("datasets", {})


# ---------------------------------------------------------------------------
# Coverage checker
# ---------------------------------------------------------------------------

def check_coverage(cmap: ContentMap, schemas: dict[str, dict]) -> list[Issue]:
    """Every required element has a section; every section has a source.

    Returns issues in a stable order so a CI diff of the output is readable.
    """
    issues: list[Issue] = []

    # -- structural integrity of the map itself ----------------------------
    seen_sections: set[str] = set()
    for s in cmap.sections:
        sid = s.get("section_id", "<missing>")
        if sid in seen_sections:
            issues.append(Issue("DUPLICATE_SECTION_ID", ERROR, sid,
                                "two sections share this identifier; citations would be ambiguous"))
        seen_sections.add(sid)

    seen_elements: set[str] = set()
    for e in cmap.elements:
        eid = e.get("element_id", "<missing>")
        if eid in seen_elements:
            issues.append(Issue("DUPLICATE_ELEMENT_ID", ERROR, eid,
                                "two RFQ elements share this identifier"))
        seen_elements.add(eid)

    # -- 1. an RFQ element with no section ---------------------------------
    for e in cmap.elements:
        eid = e["element_id"]
        if not cmap.sections_for(eid):
            issues.append(Issue("UNMAPPED_ELEMENT", ERROR, eid,
                                f"required RFQ element '{e.get('name', eid)}' is not covered "
                                f"by any section; the report would ship without it"))

    # -- 2. a section with no source, and section->element integrity -------
    for s in cmap.sections:
        sid = s.get("section_id", "<missing>")
        covers = s.get("covers", [])
        if not covers:
            issues.append(Issue("ORPHAN_SECTION", ERROR, sid,
                                "section covers no RFQ element; it is either unnecessary "
                                "or an element is missing from the map"))
        for eid in covers:
            if cmap.element(eid) is None:
                issues.append(Issue("DANGLING_ELEMENT_REF", ERROR, sid,
                                    f"covers unknown element '{eid}'"))

        inputs = s.get("required_inputs", [])
        if not inputs:
            issues.append(Issue("SECTION_WITHOUT_SOURCE", ERROR, sid,
                                "section declares no required input; prose here would rest "
                                "on nothing a reader can check"))

        # -- 3/4. dataset and field bindings -------------------------------
        for i, binding in enumerate(inputs):
            ds = binding.get("dataset")
            where = f"{sid}.required_inputs[{i}]"
            if ds not in schemas:
                issues.append(Issue("UNKNOWN_DATASET", ERROR, where,
                                    f"dataset '{ds}' is not declared in input_schemas.json"))
                continue
            known = set(schemas[ds].get("fields", []))
            declared = binding.get("fields", [])
            if not declared:
                issues.append(Issue("INPUT_WITHOUT_FIELDS", ERROR, where,
                                    f"dataset '{ds}' is bound but no field is named; "
                                    f"the section cannot state what it consumes"))
            for fname in declared:
                if fname not in known:
                    issues.append(Issue("FIELD_NOT_IN_SCHEMA", ERROR, where,
                                        f"'{fname}' is not a field of '{ds}'. Use the real "
                                        f"register field name or add the field to the schema; "
                                        f"do not invent one."))
            if not binding.get("why"):
                issues.append(Issue("INPUT_WITHOUT_RATIONALE", WARN, where,
                                    f"dataset '{ds}' is bound with no stated reason"))

        # -- report hygiene the RFQ actually depends on --------------------
        if not s.get("traceability_rule"):
            issues.append(Issue("MISSING_TRACEABILITY_RULE", ERROR, sid,
                                "no traceability rule; statements here could not be followed "
                                "back to a finding or source"))
        if not s.get("unknown_rule"):
            issues.append(Issue("MISSING_UNKNOWN_RULE", ERROR, sid,
                                "no rule for missing evidence; this is where an absent input "
                                "turns into a zero or a pass"))
        if not s.get("prompts"):
            issues.append(Issue("SECTION_WITHOUT_PROMPTS", WARN, sid,
                                "no author prompts; the template would give the writer nothing"))

    # -- the three exclusions must remain declared -------------------------
    declared_guards = {x.get("guard_class") for x in cmap.excluded}
    for required in ("audit_verdict", "individual_evaluation", "product_procurement"):
        if required not in declared_guards:
            issues.append(Issue("MISSING_EXCLUSION", ERROR, required,
                                "the work order requires this deliverable stay out of scope; "
                                "it is not declared in excluded_deliverables"))

    return issues


def errors(issues: Sequence[Issue]) -> list[Issue]:
    return [i for i in issues if i.severity == ERROR]


# ---------------------------------------------------------------------------
# Workbench verification: are the pinned field names still the real ones?
# ---------------------------------------------------------------------------

def verify_workbench(schemas: dict[str, dict], repo_root: str) -> list[Issue]:
    """Re-read the checked-in registers and compare against the pinned schema.

    Datasets marked `lane_local` have no upstream file yet and are skipped - they
    are this lane's own fixtures, declared with reused field names so a real
    register can replace them without a rename pass.
    """
    issues: list[Issue] = []
    for name, spec in sorted(schemas.items()):
        if spec.get("provenance") != "workbench_pinned":
            continue
        rel = spec.get("source_path", "")
        path = os.path.join(repo_root, rel)
        if not os.path.exists(path):
            issues.append(Issue("WORKBENCH_FILE_MISSING", WARN, name,
                                f"{rel} not found under {repo_root}; cannot verify pinned fields"))
            continue
        try:
            with open(path, newline="", encoding="utf-8") as f:
                header = next(csv.reader(f))
        except StopIteration:
            issues.append(Issue("WORKBENCH_FILE_EMPTY", ERROR, name, f"{rel} has no header row"))
            continue
        real = set(header)
        pinned = list(spec.get("fields", []))
        drifted = [p for p in pinned if p not in real]
        if drifted:
            issues.append(Issue("SCHEMA_DRIFT", ERROR, name,
                                f"pinned field(s) {drifted} are no longer in {rel}; "
                                f"the upstream register changed shape"))
        added = [r for r in header if r not in set(pinned)]
        if added:
            issues.append(Issue("SCHEMA_NEW_FIELDS", WARN, name,
                                f"{rel} now carries field(s) {added} the map does not consume yet"))
    return issues


# ---------------------------------------------------------------------------
# Fixture loading (synthetic, labeled fiction)
# ---------------------------------------------------------------------------

def load_fixture(schemas: dict[str, dict], dataset: str,
                 fixtures_dir: str = DEFAULT_FIXTURES) -> list[dict]:
    """Load a dataset's synthetic rows, if this lane carries a fixture for it."""
    candidates = [
        os.path.join(fixtures_dir, f"synthetic_{dataset}.csv"),
        os.path.join(fixtures_dir, os.path.basename(schemas.get(dataset, {}).get("source_path", ""))),
    ]
    for c in candidates:
        if c and os.path.exists(c):
            with open(c, newline="", encoding="utf-8") as f:
                return list(csv.DictReader(f))
    return []


def load_all_fixtures(schemas: dict[str, dict],
                      fixtures_dir: str = DEFAULT_FIXTURES) -> dict[str, list[dict]]:
    return {ds: load_fixture(schemas, ds, fixtures_dir) for ds in schemas}


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

_FICTION_BANNER = (
    "> **SYNTHETIC EXAMPLE - NOT A UNIVERSITY FINDING.** Every group, finding, "
    "identifier, date and number below is fiction, written to exercise the report "
    "structure. Nothing here describes the University of Iowa.\n"
)

_TEMPLATE_BANNER = (
    "> **EDITABLE TEMPLATE.** Replace every `<...>` placeholder. Do not delete a "
    "section to hide a gap: a section with nothing to report says so and cites the "
    "open question instead. Missing evidence stays `UNKNOWN` - it never becomes a "
    "zero, a pass, or a maturity score.\n"
)


def _md_table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> str:
    def esc(v: Any) -> str:
        s = "" if v is None else str(v)
        return s.replace("|", "\\|").replace("\n", " ")
    out = ["| " + " | ".join(esc(h) for h in headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(esc(c) for c in r) + " |")
    return "\n".join(out)


def _blank(v: str) -> str:
    """An empty cell is reported as UNKNOWN, never as an implied zero or pass."""
    v = (v or "").strip()
    return v if v else UNKNOWN_TOKEN


def render_template(cmap: ContentMap, schemas: dict[str, dict]) -> str:
    """The editable report template: structure, prompts, and input contracts."""
    L: list[str] = []
    L.append("# University of Iowa RFQ 18649 - Assessment Report")
    L.append("")
    L.append("**Status:** `<DRAFT | FINAL>`  ")
    L.append("**Prepared by:** `<assessment team>`  ")
    L.append("**Reporting period:** `<start>` to `<end>`  ")
    L.append("**Report structure:** `" + cmap.raw.get("map_id", "") + "`")
    L.append("")
    L.append(_TEMPLATE_BANNER)
    L.append("## Scope boundary")
    L.append("")
    L.append("This assessment describes current practice against reference frameworks used as "
             "interview and artifact prompts. It is not a formal audit and issues no compliance "
             "determination, certification or attestation. It assesses organizational practice; "
             "no statement rates, ranks or evaluates a named individual. It describes capabilities "
             "the University may need; no vendor selection or product purchase is recommended.")
    L.append("")
    for x in cmap.excluded:
        L.append(f"- **Out of scope - {x['name']}.** {x['why']}")
    L.append("")
    L.append("---")
    L.append("")
    for s in cmap.sections:
        L.append(f"## {s['number']}. {s['title']}")
        L.append("")
        L.append(f"*Audience: {s.get('audience', 'all')}. Covers: "
                 f"{', '.join(s.get('covers', []))}.*")
        L.append("")
        L.append(f"**Purpose.** {s.get('purpose', '')}")
        L.append("")
        L.append("**Inputs this section requires**")
        L.append("")
        L.append(_md_table(
            ["dataset", "fields consumed", "why"],
            [[b["dataset"], ", ".join(f"`{x}`" for x in b.get("fields", [])), b.get("why", "")]
             for b in s.get("required_inputs", [])]))
        L.append("")
        L.append(f"**Traceability rule.** {s.get('traceability_rule', '')}")
        L.append("")
        L.append(f"**Missing-evidence rule.** {s.get('unknown_rule', '')}")
        L.append("")
        L.append("**Write this section by answering:**")
        L.append("")
        for p in s.get("prompts", []):
            L.append(f"- {p}")
        L.append("")
        L.append("> `<section content here>`")
        L.append("")
        L.append("---")
        L.append("")
    return "\n".join(L)


def _matrix_block(rows: list[dict]) -> str:
    """The 12-cell view. An unassessed cell stays visibly unassessed."""
    groups = ["ESS", "RIS", "IAM"]
    areas = ["SD", "SEC", "DEP", "AI"]
    idx = {(r.get("group"), r.get("area")): r for r in rows}
    out = [_md_table(
        ["group \\ area", "SD software dev", "SEC security", "DEP deployment/ops", "AI readiness"],
        [[g] + [(lambda r: f"{_blank(r.get('status'))} ({_blank(r.get('confidence'))}) "
                           f"{r.get('finding_id', '')}".strip()
                 if r else f"{UNKNOWN_TOKEN} - not assessed")(idx.get((g, a)))
                for a in areas]
         for g in groups])]
    assessed = [r for r in rows if r.get("status") not in ("", UNKNOWN_TOKEN, None)]
    out.append("")
    out.append(f"*{len(assessed)} of 12 cells carry an assessed status. "
               f"Cells shown as `{UNKNOWN_TOKEN} - not assessed` are a statement about the "
               f"evidence collected, not about the group, and are excluded from every count "
               f"of assessed cells rather than counted as zero.*")
    return "\n".join(out)


def render_sample(cmap: ContentMap, schemas: dict[str, dict],
                  data: dict[str, list[dict]]) -> str:
    """A populated synthetic report rendered through the same structure."""
    matrix = data.get("finding_matrix", [])
    evidence = data.get("evidence_register", [])
    recs = data.get("recommendation_register", [])
    themes = data.get("theme_register", [])
    peers = data.get("peer_context_table", [])

    L: list[str] = []
    L.append("# University of Iowa RFQ 18649 - Assessment Report (SYNTHETIC SAMPLE)")
    L.append("")
    L.append(_FICTION_BANNER)
    L.append("**Status:** SYNTHETIC SAMPLE  ")
    L.append("**Report structure:** `" + cmap.raw.get("map_id", "") + "`  ")
    L.append("**Purpose:** demonstrate that the structure accepts the planned matrix and "
             "register outputs and renders a complete report from them.")
    L.append("")
    L.append("## Scope boundary")
    L.append("")
    L.append("This assessment is not a formal audit and issues no compliance determination, "
             "certification or attestation. No statement rates, ranks or evaluates a named "
             "individual. No vendor selection or product purchase is recommended.")
    L.append("")
    L.append("---")
    L.append("")

    for s in cmap.sections:
        sid = s["section_id"]
        L.append(f"## {s['number']}. {s['title']}")
        L.append("")

        if sid == "SEC-01":
            supported = [r for r in matrix if r.get("status") == "SUPPORTED"]
            gaps = [r for r in matrix if r.get("status") in ("PARTIAL", "CONFLICT")]
            unassessed = [r for r in matrix if r.get("status") == UNKNOWN_TOKEN]
            L.append(f"Twelve group-by-area cells were in scope. {len(matrix)} were reached; "
                     f"{len(supported)} are supported by direct current evidence, "
                     f"{len(gaps)} are partial or carry conflicting evidence, and "
                     f"{len(unassessed)} could not be assessed with the evidence supplied.")
            L.append("")
            for r in supported[:2]:
                L.append(f"- **Holds up.** {r.get('statement')} ({r['finding_id']}, "
                         f"confidence {r.get('confidence')}).")
            for r in gaps[:2]:
                L.append(f"- **Does not yet hold up.** {r.get('statement')} ({r['finding_id']}, "
                         f"confidence {r.get('confidence')}). {r.get('scope_limit')}")
            for r in unassessed:
                L.append(f"- **Not assessed.** {r.get('group')}/{r.get('area')} "
                         f"({r['finding_id']}): {r.get('scope_limit')} "
                         f"Resolving question: {r.get('follow_up_question')}")
            L.append("")
            near = [r for r in recs if r.get("horizon") == "0-90"]
            if near:
                L.append("Proposed in the first 90 days:")
                L.append("")
                for r in near:
                    L.append(f"- {r['recommendation_id']}: {r.get('statement')} "
                             f"(from {r.get('finding_refs')})")
            L.append("")

        elif sid == "SEC-02":
            L.append("In scope: ESS, RIS and IAM across software development (SD), security (SEC), "
                     "deployment and operations (DEP), and AI readiness (AI) - twelve cells.")
            L.append("")
            L.append(_md_table(["group", "areas reached", "areas not assessed"],
                               [[g,
                                 ", ".join(sorted(r["area"] for r in matrix
                                                  if r.get("group") == g
                                                  and r.get("status") != UNKNOWN_TOKEN)) or "none",
                                 ", ".join(sorted(r["area"] for r in matrix
                                                  if r.get("group") == g
                                                  and r.get("status") == UNKNOWN_TOKEN)) or "none"]
                                for g in ("ESS", "RIS", "IAM")]))
            L.append("")

        elif sid == "SEC-03":
            kinds: dict[str, int] = {}
            for e in evidence:
                kinds[e.get("source_type", UNKNOWN_TOKEN)] = kinds.get(e.get("source_type", UNKNOWN_TOKEN), 0) + 1
            L.append(f"{len(evidence)} synthetic evidence items were collected across "
                     f"{len(kinds)} source types.")
            L.append("")
            L.append(_md_table(["source type", "items"],
                               [[k, str(v)] for k, v in sorted(kinds.items())]))
            L.append("")
            L.append("Framework references were used as interview and artifact prompts. A framework "
                     "practice is a prompt, not a criterion, and no cell is scored against one.")
            L.append("")

        elif sid == "SEC-04":
            L.append("Confidence is recorded on five dimensions and is never averaged into a single "
                     "number. The dimensions are reported alongside each evidence item in Appendix A.")
            L.append("")
            dist: dict[str, int] = {}
            for e in evidence:
                dist[e.get("confidence", UNKNOWN_TOKEN)] = dist.get(e.get("confidence", UNKNOWN_TOKEN), 0) + 1
            L.append(_md_table(["confidence", "evidence items", "meaning"],
                               [[k, str(v),
                                 {"HIGH": "direct, current, representative, corroborated",
                                  "MODERATE": "direct but narrow, or current without independent corroboration",
                                  "LOW": "indirect, stale, single-source, or uncorroborated",
                                  "NOT_EVIDENCED": "no source was observed for the claim",
                                  "UNRESOLVED": "material sources disagree and the conflict is open",
                                  }.get(k, "")]
                                for k, v in sorted(dist.items())]))
            L.append("")
            L.append("`NOT_EVIDENCED` means no source was reviewed. It is not a negative finding "
                     "about the group, and it is not a zero.")
            L.append("")

        elif sid == "SEC-05":
            if peers:
                L.append(_md_table(
                    ["peer", "measure", "value", "denominator/scope", "comparison status", "note"],
                    [[p.get("peer"), p.get("metric_or_measure"), p.get("value"),
                      p.get("denominator_or_scope"), p.get("comparison_status"),
                      p.get("comparability_notes")] for p in peers]))
                L.append("")
            L.append("Every row above carries its own comparison status. Rows marked `context_only` "
                     "or `not_comparable_without_normalization` cannot support a comparison and are "
                     "presented as context. No percentile, ranking or standing against peers is "
                     "stated anywhere in this report.")
            L.append("")

        elif sid == "SEC-06":
            L.append(_matrix_block(matrix))
            L.append("")

        elif sid in ("SEC-07", "SEC-08", "SEC-09"):
            grp = {"SEC-07": "ESS", "SEC-08": "RIS", "SEC-09": "IAM"}[sid]
            rows = [r for r in matrix if r.get("group") == grp]
            for r in rows:
                L.append(f"### {r['finding_id']} - {grp} / {r.get('area')} "
                         f"({_blank(r.get('status'))}, confidence {_blank(r.get('confidence'))})")
                L.append("")
                L.append(r.get("statement", ""))
                L.append("")
                L.append(f"*Scope limit:* {r.get('scope_limit')}")
                L.append("")
                supp = [e for e in evidence if e.get("finding_id") == r["finding_id"]]
                if supp:
                    L.append(_md_table(
                        ["evidence", "type", "claim", "directness", "recency",
                         "representativeness", "corroboration", "confidence"],
                        [[e.get("evidence_id"), e.get("source_type"), e.get("claim"),
                          e.get("directness"), e.get("recency"), e.get("representativeness"),
                          e.get("corroboration"), e.get("confidence")] for e in supp]))
                else:
                    L.append(f"*No evidence item is registered for this finding - "
                             f"status {UNKNOWN_TOKEN}.*")
                L.append("")
                if r.get("follow_up_question"):
                    L.append(f"*Open question:* {r['follow_up_question']}")
                    L.append("")

        elif sid == "SEC-10":
            for t in themes:
                L.append(f"### {t['theme_id']} - {t.get('statement')}")
                L.append("")
                L.append(f"*Spans:* {t.get('groups_spanned')} / {t.get('areas_spanned')}  ")
                L.append(f"*Findings:* {t.get('finding_refs')}  ")
                L.append(f"*Counter-evidence:* {_blank(t.get('counter_evidence'))}  ")
                L.append(f"*Scope limit:* {t.get('scope_limit')}")
                L.append("")
            L.append("Each theme names the individual findings it spans. A theme is a reading of "
                     "those findings, not a replacement for them; the findings remain the record.")
            L.append("")

        elif sid == "SEC-11":
            for g in ("ESS", "RIS", "IAM", "CROSS"):
                rows = [r for r in recs if r.get("group") == g]
                if not rows:
                    continue
                L.append(f"### {g}")
                L.append("")
                L.append(_md_table(
                    ["id", "recommendation", "from findings", "rationale", "resource note", "depends on"],
                    [[r["recommendation_id"], r.get("statement"), r.get("finding_refs"),
                      r.get("rationale"), _blank(r.get("resource_note")),
                      _blank(r.get("dependency"))] for r in rows]))
                L.append("")
            L.append("Each recommendation names the findings that motivate it and does not inherit "
                     "their confidence. Recommendations describe capabilities and decisions; "
                     "selecting or purchasing a product is the University's own process.")
            L.append("")

        elif sid == "SEC-12":
            for h, label in (("0-90", "0-90 days"), ("90-180", "90-180 days"),
                             ("180+", "180+ days"), (UNKNOWN_TOKEN, "Unsequenced - estimate missing")):
                rows = [r for r in recs if (r.get("horizon") or UNKNOWN_TOKEN) == h]
                L.append(f"### {label}")
                L.append("")
                if rows:
                    L.append(_md_table(["id", "recommendation", "depends on", "resource note"],
                                       [[r["recommendation_id"], r.get("statement"),
                                         _blank(r.get("dependency")), _blank(r.get("resource_note"))]
                                        for r in rows]))
                else:
                    L.append("*No items.*")
                L.append("")
            L.append(f"An item whose horizon is `{UNKNOWN_TOKEN}` sits in the unsequenced bucket with "
                     f"the missing input named. It is not defaulted into a later phase, which would "
                     f"present a guess as a plan.")
            L.append("")

        elif sid == "SEC-13":
            L.append(_md_table(
                ["evidence", "finding", "group/area", "type", "source", "captured", "represents",
                 "claim", "scope limit", "state", "confidence"],
                [[e.get("evidence_id"), e.get("finding_id"),
                  f"{e.get('group')}/{e.get('area')}", e.get("source_type"), e.get("source_ref"),
                  e.get("captured_at"), e.get("represented_period"), e.get("claim"),
                  e.get("scope_limit"), e.get("evidence_state"), e.get("confidence")]
                 for e in evidence]))
            L.append("")
            cited = {r["finding_id"] for r in matrix}
            backed = {e.get("finding_id") for e in evidence}
            missing = sorted(cited - backed)
            if missing:
                L.append(f"*Findings with no registered evidence item: {', '.join(missing)}. "
                         f"These are carried as {UNKNOWN_TOKEN} in the matrix and are listed in "
                         f"Appendix C.*")
                L.append("")

        elif sid == "SEC-14":
            L.append("*In a real engagement this appendix is rendered from the landed source and "
                     "version registers (`source_version_register`, `policy_context_register`), "
                     "pinning every framework to the version actually used. This synthetic sample "
                     "does not restate those registers.*")
            L.append("")

        elif sid == "SEC-15":
            open_rows = [r for r in matrix
                         if r.get("status") in (UNKNOWN_TOKEN, "PARTIAL", "CONFLICT")]
            L.append(_md_table(["finding", "group/area", "status", "what is unresolved",
                                "what would resolve it"],
                               [[r["finding_id"], f"{r.get('group')}/{r.get('area')}",
                                 r.get("status"), r.get("scope_limit"),
                                 _blank(r.get("follow_up_question"))] for r in open_rows]))
            L.append("")
            L.append("This appendix exists so that an absent input never has to become a zero, a "
                     "pass or a rating anywhere else in the report.")
            L.append("")

        else:
            L.append("*(no sample renderer for this section)*")
            L.append("")

        L.append("---")
        L.append("")

    return "\n".join(L)


def content_map_rows(cmap: ContentMap) -> list[list[str]]:
    """Flat element -> section -> input view, for the operator-facing CSV."""
    rows: list[list[str]] = []
    for e in cmap.elements:
        secs = cmap.sections_for(e["element_id"])
        if not secs:
            rows.append([e["element_id"], e["name"], "", "", "", "", e.get("must_not", "")])
            continue
        for s in secs:
            for b in s.get("required_inputs", []):
                rows.append([e["element_id"], e["name"], s["section_id"],
                             f"{s['number']}. {s['title']}", b.get("dataset", ""),
                             "; ".join(b.get("fields", [])), e.get("must_not", "")])
    return rows


CONTENT_MAP_HEADERS = ["element_id", "rfq_element", "section_id", "section",
                       "required_dataset", "required_fields", "element_must_not"]


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _report_issues(issues: Sequence[Issue], title: str) -> None:
    errs = errors(issues)
    warns = [i for i in issues if i.severity == WARN]
    print(title)
    print("=" * len(title))
    print(f"errors: {len(errs)}   warnings: {len(warns)}")
    for i in issues:
        print("  " + str(i))
    if not issues:
        print("  (none)")
    print()


def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="UIOWA-082 report structure: check and render.")
    ap.add_argument("--map", default=DEFAULT_MAP)
    ap.add_argument("--schemas", default=DEFAULT_SCHEMAS)
    ap.add_argument("--fixtures", default=DEFAULT_FIXTURES)
    ap.add_argument("--check", action="store_true", help="run the coverage checker")
    ap.add_argument("--verify-workbench", metavar="REPO_ROOT", default=None,
                    help="re-read the landed registers and fail on pinned-field drift")
    ap.add_argument("--render-template", metavar="PATH", default=None)
    ap.add_argument("--render-sample", metavar="PATH", default=None)
    ap.add_argument("--render-map-csv", metavar="PATH", default=None)
    ap.add_argument("--scope-guard", action="store_true",
                    help="run the scope guard over the rendered template and sample")
    a = ap.parse_args(argv)

    cmap = load_map(a.map)
    schemas = load_schemas(a.schemas)
    rc = 0

    if a.check or not any([a.render_template, a.render_sample, a.render_map_csv,
                           a.verify_workbench, a.scope_guard]):
        issues = check_coverage(cmap, schemas)
        _report_issues(issues, "COVERAGE CHECK")
        print(f"{len(cmap.elements)} RFQ elements -> {len(cmap.section_ids)} sections")
        for e in cmap.elements:
            secs = ", ".join(s["section_id"] for s in cmap.sections_for(e["element_id"])) or "NONE"
            print(f"  {e['element_id']}  {e['name'][:46]:<46} -> {secs}")
        print()
        if errors(issues):
            rc = 1

    if a.verify_workbench:
        issues = verify_workbench(schemas, a.verify_workbench)
        _report_issues(issues, "WORKBENCH SCHEMA VERIFICATION")
        if errors(issues):
            rc = 1

    data = load_all_fixtures(schemas, a.fixtures)

    if a.render_template:
        text = render_template(cmap, schemas)
        with open(a.render_template, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"wrote {a.render_template} ({len(text)} bytes)")

    if a.render_sample:
        text = render_sample(cmap, schemas, data)
        with open(a.render_sample, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"wrote {a.render_sample} ({len(text)} bytes)")

    if a.render_map_csv:
        with open(a.render_map_csv, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(CONTENT_MAP_HEADERS)
            w.writerows(content_map_rows(cmap))
        print(f"wrote {a.render_map_csv}")

    if a.scope_guard:
        import scope_guard
        # Scan the RENDERED documents, not content_map.json. The guard reads
        # prose at the sentence level, and raw JSON splits a record's
        # scope-boundary context across lines - the exclusion's `name` ("Employee
        # or individual performance evaluation") lands on one line and the `why`
        # that disclaims it on another, so the neutralizing context is not in the
        # window. Rendered, that same record reads "Out of scope - Employee or
        # individual performance evaluation. This engagement ...", which is the
        # form a reader actually sees and the form the guard should judge. Every
        # string in the map reaches the template, so nothing goes unchecked.
        texts = [("template", render_template(cmap, schemas)),
                 ("sample", render_sample(cmap, schemas, data))]
        hits = []
        for name, t in texts:
            hits.extend(scope_guard.scan_text(t, source_id=name))
        print(scope_guard.render(hits, show_neutralized=True))
        if scope_guard.flagged(hits):
            rc = 1

    return rc


if __name__ == "__main__":
    raise SystemExit(main())
