"""Creator reward campaign desk.

Successor entrypoint over the reviewed 5afe6322 generation. The business logic lives in
``server_legacy`` byte-for-byte; this module replaces SQLite custody and startup database
identity. Descriptor platforms open SQLite through the desk's already-held descriptor namespace
path, so a public-path swap cannot redirect I/O. Existing nonempty databases are accepted only
when their complete application schema matches the exact frozen legacy generation before any
identity PRAGMA or product DDL can mutate them.
"""

import os as _os
import stat as _stat
import sqlite3 as _sqlite3

import server_legacy as _legacy

# Re-export the established public and test surface. Function objects defined by the predecessor
# retain server_legacy as their globals; after Desk is replaced below, main()/demo/API paths all
# instantiate this successor Desk.
for _name, _value in vars(_legacy).items():
    if _name not in {'__name__', '__file__', '__package__', '__loader__', '__spec__'}:
        globals().setdefault(_name, _value)


def _legacy_schema_sql():
    """Recover the exact frozen generation DDL from the predecessor function object.

    This avoids maintaining a second hand-copied schema. The predecessor is preserved byte-exact;
    its constructor has one application DDL string containing both the first and last desk tables.
    """
    candidates = [
        value for value in _legacy.Desk.__init__.__code__.co_consts
        if isinstance(value, str)
        and 'CREATE TABLE IF NOT EXISTS brands (' in value
        and 'CREATE TABLE IF NOT EXISTS operations (' in value
    ]
    if len(candidates) != 1:
        raise RuntimeError('frozen creator-reward schema literal is missing or ambiguous')
    return candidates[0]


def _schema_fingerprint(db):
    """Canonical application-object signature; internal sqlite_* objects are intentionally ignored."""
    rows = db.execute(
        "SELECT type,name,tbl_name,sql FROM sqlite_master "
        "WHERE type IN ('table','index','trigger','view') AND name NOT LIKE 'sqlite_%' "
        "ORDER BY type,name,tbl_name"
    ).fetchall()
    return tuple(
        (str(row[0]), str(row[1]), str(row[2]), None if row[3] is None else ' '.join(str(row[3]).split()))
        for row in rows
    )


def _expected_schema_fingerprint():
    db = _sqlite3.connect(':memory:')
    try:
        db.executescript(_legacy_schema_sql())
        return _schema_fingerprint(db)
    finally:
        db.close()


_EXPECTED_SCHEMA_FINGERPRINT = _expected_schema_fingerprint()


class Desk(_legacy.Desk):
    """Desk with positive SQLite->pinned-file binding and positive startup schema identity.

    The predecessor tried to infer the connection's file from process-wide descriptor deltas and
    treated one table name (``brands``) as sufficient evidence that an identity-less SQLite file
    belonged to this product. The successor does neither.

    On POSIX-like hosts with a descriptor namespace, ``sqlite3.connect`` receives
    ``<descriptor-table>/<self._handle>``: a kernel reference to the file already opened and
    pinned by ``_pin``. A swap of ``self.path`` therefore cannot redirect the connection. We
    additionally require the public pathname to denote that same inode immediately before and
    after the open; a persistent rename/repoint is a 503. A transient swap restored between those
    fences may be observationally invisible, but it cannot receive reads or writes.

    A nonempty existing database is read-only inspected before adoption. Its connection/header
    identity must agree and its complete non-internal sqlite_master schema must equal the schema
    generated by the exact frozen predecessor DDL. Only then may an identity-less legacy desk be
    given an identity; identified desks must also carry the predecessor's positive odd identity
    generation. Foreign or incompatible SQLite files are refused before any product mutation.
    """

    def _assert_public_path_pinned(self):
        try:
            current = _os.lstat(self.path)
        except OSError as exc:
            raise _legacy.DeskError(_legacy.SUBSTITUTED_MESSAGE, 503) from exc
        if (not _stat.S_ISREG(current.st_mode)
                or (current.st_dev, current.st_ino) != self.pinned):
            raise _legacy.DeskError(_legacy.SUBSTITUTED_MESSAGE, 503)

    def _descriptor_target(self):
        table = _legacy.DESCRIPTOR_TABLE
        if not table:
            raise _legacy.DeskError(_legacy.UNSUPPORTED_MESSAGE, 503)
        target = _os.path.join(table, str(self._handle))
        try:
            found = _os.stat(target)
        except OSError as exc:
            raise _legacy.DeskError(_legacy.SUBSTITUTED_MESSAGE, 503) from exc
        if (not _stat.S_ISREG(found.st_mode)
                or (found.st_dev, found.st_ino) != self.pinned):
            raise _legacy.DeskError(_legacy.SUBSTITUTED_MESSAGE, 503)
        return target

    def _open(self):
        """Open one proven SQLite session while holding the predecessor's process desk lock."""
        _legacy._DESK_LOCK.acquire()
        db = None
        try:
            self._assert_public_path_pinned()
            if _legacy.CUSTODY_PROOF == 'descriptor':
                target = self._descriptor_target()
            else:
                # Windows: the retained handle prevents rename/replace while the desk lives.
                target = self.path
            db = _sqlite3.connect(target, timeout=10)
            # Re-fence both names after the open. On descriptor platforms the connection was
            # already unredirectable; this second public-path fence makes persistent substitution
            # fail closed. The descriptor target itself must still name the held inode.
            self._assert_public_path_pinned()
            if _legacy.CUSTODY_PROOF == 'descriptor':
                self._descriptor_target()
            else:
                try:
                    current = _os.stat(self.path)
                except OSError as exc:
                    raise _legacy.DeskError(_legacy.SUBSTITUTED_MESSAGE, 503) from exc
                if (current.st_dev, current.st_ino) != self.pinned:
                    raise _legacy.DeskError(_legacy.SUBSTITUTED_MESSAGE, 503)
            db.row_factory = _sqlite3.Row
            db.execute('PRAGMA foreign_keys=ON')
        except BaseException:
            try:
                if db is not None:
                    db.close()
            finally:
                _legacy._DESK_LOCK.release()
            raise
        return _legacy._Session(db)

    def _adopt(self, db):
        """Adopt only an empty file or a positively recognized complete desk generation."""
        seen = self._connection_identity(db)
        header = self._header_identity()

        if header is None:
            # New O_CREAT file: SQLite must still see an untouched zero-page database. This is the
            # only path allowed to mint identity before an application schema exists.
            if seen != (0, 0) or int(db.execute('PRAGMA page_count').fetchone()[0]) != 0:
                raise _legacy.DeskError(_legacy.SUBSTITUTED_MESSAGE, 503)
            identity = (_legacy.secrets.randbits(31) | 1, _legacy.secrets.randbits(31) | 1)
            db.execute('PRAGMA application_id=%d' % identity[0])
            db.execute('PRAGMA user_version=%d' % identity[1])
            return identity

        # Everything below is an existing nonempty SQLite file. Reads only until the complete
        # generation is proven: no identity PRAGMA and no product DDL may precede this check.
        if seen != header:
            raise _legacy.DeskError(_legacy.SUBSTITUTED_MESSAGE, 503)
        try:
            schema = _schema_fingerprint(db)
        except _sqlite3.DatabaseError as exc:
            raise _legacy.DeskError(_legacy.NOT_A_DATABASE_MESSAGE, 503) from exc
        if schema != _EXPECTED_SCHEMA_FINGERPRINT:
            raise _legacy.DeskError(_legacy.NOT_A_DATABASE_MESSAGE, 503)

        if seen == (0, 0):
            # Exact pre-identity legacy generation: now and only now is one-time adoption safe.
            identity = (_legacy.secrets.randbits(31) | 1, _legacy.secrets.randbits(31) | 1)
            db.execute('PRAGMA application_id=%d' % identity[0])
            db.execute('PRAGMA user_version=%d' % identity[1])
            return identity

        # Frozen predecessor identity generation always minted two positive odd 31-bit values.
        if any(value <= 0 or not (value & 1) for value in seen):
            raise _legacy.DeskError(_legacy.NOT_A_DATABASE_MESSAGE, 503)
        return header


# Every predecessor function that resolves Desk dynamically (main, demo setup, callers importing
# server_legacy indirectly) now receives the successor class.
_legacy.Desk = Desk

# Make the successor explicit for direct imports after the predecessor export loop.
globals()['Desk'] = Desk


if __name__ == '__main__':
    raise SystemExit(_legacy.main())
